Necesitamos cambiar el nombre de las imágenes para añadir la info de la lesión en el nombre. Es más cómodo y además nos permite separar por mass y calcification, que es necesario para la segmentación y más cosas.
Para ello, usaremos los csv que traen la info de cada imagen de INbreast:

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
INbreast = pd.read_csv('INbreastExcel.csv', sep = ';')
INbreast.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 412 entries, 0 to 411
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Patient ID                      410 non-null    object
 1   Patient age                     410 non-null    object
 2   Laterality                      410 non-null    object
 3   View                            410 non-null    object
 4   Acquisition date                410 non-null    float64
 5   File Name                       410 non-null    float64
 6   ACR                             411 non-null    object
 7   Bi-Rads                         411 non-null    object
 8   Mass                            109 non-null    object
 9   Micros                          309 non-null    object
 10  Distortion                      5 non-null      object
 11  Asymmetry                       15 non-null     object
 12  Findings Notes (in Portuguese)  410 non-null    object
 13  Other Notes                     1 non-null      object
 14  Lesion Annotation Status        71 non-null     object
 15  Pectoral Muscle Annotation      6 non-null      object
 16  Other Annotations               7 non-null      object
 17  Unnamed: 17                     0 non-null      float64
 18  Unnamed: 18                     0 non-null      float64
 19  Unnamed: 19                     0 non-null      float64
 20  Unnamed: 20                     0 non-null      float64
 21  Unnamed: 21                     0 non-null      float64
dtypes: float64(7), object(15)
memory usage: 70.9+ KB

In [2]:
INbreast

,Patient ID,Patient age,Laterality,View,Acquisition date,File Name,ACR,Bi-Rads,Mass,Micros,Distortion,Asymmetry,Findings Notes (in Portuguese),Other Notes,Lesion Annotation Status,Pectoral Muscle Annotation,Other Annotations,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,removed,removed,R,CC,201001.0,22678622.0,4,1,NaN,NaN,NaN,NaN,normal,NaN,No annotation (Normal),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,removed,removed,L,CC,201001.0,22678646.0,4,3,X,NaN,NaN,NaN,nódulo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,removed,removed,R,MLO,201001.0,22678670.0,4,1,NaN,NaN,NaN,NaN,normal,NaN,No annotation (Normal),NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,removed,removed,L,MLO,201001.0,22678694.0,4,3,X,NaN,NaN,NaN,nódulo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,removed,removed,R,CC,201001.0,22614074.0,2,5,X,X,NaN,NaN,nódulo QSE + micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,removed,removed,L,CC,201001.0,22614097.0,2,2,X,X,NaN,NaN,nodulo + micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,removed,removed,R,MLO,201001.0,22614127.0,2,5,X,X,NaN,NaN,nódulo QSE + micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,removed,removed,L,MLO,201001.0,22614150.0,2,2,X,X,NaN,NaN,nódulo + micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,removed,removed,L,MLO,201001.0,50997434.0,3,2,NaN,X,NaN,NaN,micro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,removed,removed,R,MLO,201001.0,50997461.0,3,4a,X,X,NaN,NaN,nodulo QSE + micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,removed,removed,L,CC,201001.0,50997488.0,3,2,NaN,X,NaN,NaN,micro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,removed,removed,R,CC,201001.0,50997515.0,3,4a,X,X,NaN,NaN,nodulo QSE + micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,removed,removed,L,MLO,200801.0,24055445.0,1,4c,X,X,NaN,NaN,Nódulo + micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,removed,removed,R,MLO,200801.0,24055464.0,1,4c,X,X,NaN,NaN,Nódulo + micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,removed,removed,L,CC,200801.0,24055483.0,1,4c,X,X,NaN,NaN,nódulo +micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,removed,removed,R,CC,200801.0,24055502.0,1,4c,X,X,NaN,NaN,Nódulo + micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,removed,removed,R,CC,201001.0,22580192.0,2,3,X,NaN,NaN,NaN,nódulo benigno,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,removed,removed,L,CC,201001.0,22580218.0,2,1,NaN,NaN,NaN,NaN,normal,NaN,No annotation (Normal),NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,removed,removed,R,MLO,201001.0,22580244.0,2,3,X,NaN,NaN,NaN,nodulo benigno,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,removed,removed,L,MLO,201001.0,22580270.0,2,1,NaN,NaN,NaN,NaN,normal,NaN,No annotation (Normal),NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,removed,removed,R,CC,201001.0,50998032.0,3,2,NaN,X,NaN,NaN,micros + calcificação vasos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,removed,removed,L,MLO,201001.0,50998059.0,3,5,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,removed,removed,R,MLO,201001.0,50998086.0,3,2,NaN,X,NaN,NaN,micros + calcificação vasos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,removed,removed,L,CC,201001.0,50998113.0,3,5,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,removed,removed,L,MLO,201001.0,50997742.0,1,3,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,removed,removed,R,MLO,201001.0,50997769.0,1,3,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,removed,removed,L,CC,201001.0,50997796.0,1,3,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,removed,removed,R,CC,201001.0,50997823.0,1,3,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,removed,removed,R,CC,201001.0,22670620.0,1,2,X,NaN,NaN,NaN,nódulo QSE - já biopsado - fibroadenoma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,removed,removed,L,CC,201001.0,22670643.0,1,1,NaN,NaN,NaN,NaN,normal,NaN,No annotation (Normal),NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,removed,removed,R,MLO,201001.0,22670673.0,1,2,X,NaN,NaN,NaN,nódulo QSE - já biopsado - fibroadenoma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,removed,removed,L,MLO,201001.0,22670703.0,1,1,NaN,NaN,NaN,NaN,normal,NaN,No annotation (Normal),NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,removed,removed,L,MLO,201001.0,53581379.0,1,1,NaN,NaN,NaN,NaN,normal,NaN,No annotation (Normal),NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,removed,removed,R,MLO,201001.0,53581406.0,1,6,X,NaN,NaN,NaN,nodulo QSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,removed,removed,L,CC,201001.0,53581433.0,1,1,NaN,NaN,NaN,NaN,normal,NaN,No annotation (Normal),NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,removed,removed,R,CC,201001.0,53581460.0,1,6,X,NaN,NaN,NaN,nodulo QSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,removed,removed,L,MLO,200802.0,24065833.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,removed,removed,R,MLO,200802.0,24065860.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,removed,removed,L,CC,200802.0,24065887.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,removed,removed,R,CC,200802.0,24065914.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,removed,removed,L,MLO,200901.0,24055877.0,1,2,NaN,X,NaN,NaN,micro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,removed,removed,R,MLO,200901.0,24055904.0,1,2,NaN,X,NaN,NaN,calcificações,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,removed,removed,L,CC,200901.0,24055931.0,1,2,NaN,X,NaN,NaN,micro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,removed,removed,R,CC,200901.0,24055958.0,1,2,NaN,X,NaN,NaN,calcificações,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,removed,removed,L,MLO,201001.0,53587427.0,2,2,NaN,X,NaN,NaN,micro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,removed,removed,R,MLO,201001.0,53587454.0,2,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,removed,removed,L,CC,201001.0,53587481.0,2,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,removed,removed,R,CC,201001.0,53587508.0,2,2,NaN,X,NaN,NaN,micro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,removed,removed,L,MLO,201001.0,51049462.0,2,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,removed,removed,R,MLO,201001.0,51049489.0,2,2,NaN,X,NaN,NaN,microcalcificações,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,removed,removed,L,CC,201001.0,51049516.0,2,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,removed,removed,R,CC,201001.0,51049543.0,2,2,NaN,X,NaN,NaN,calcificações,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,removed,removed,L,MLO,200901.0,51049628.0,2,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,removed,removed,R,MLO,200901.0,51049655.0,2,2,NaN,X,NaN,NaN,calcificações,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,removed,removed,L,CC,200901.0,51049682.0,2,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,removed,removed,R,CC,200901.0,51070197.0,2,2,NaN,X,NaN,NaN,calcificações,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,removed,removed,L,MLO,201001.0,53580611.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,removed,removed,R,MLO,201001.0,53580638.0,1,3,NaN,X,,NaN,microcalcificações QSE - junto ao musculo peit...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,removed,removed,L,CC,201001.0,53580665.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,removed,removed,R,CC,201001.0,53580692.0,1,3,NaN,X,NaN,NaN,microcalcificações QSE - junto ao musculo peit...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,removed,removed,L,MLO,201001.0,53586960.0,1,2,X,X,NaN,NaN,pós-cirurgia - nódulo com regiao espiculada+ m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,removed,removed,R,MLO,201001.0,53586987.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,removed,removed,L,CC,201001.0,53587014.0,1,2,X,X,NaN,NaN,pós-cirurgia - nódulo com regiao espiculada+ m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,removed,removed,R,CC,201001.0,53587041.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,removed,removed,L,MLO,200902.0,51048891.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,removed,removed,R,MLO,200902.0,51048918.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,removed,removed,L,CC,200902.0,51048945.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,removed,removed,R,CC,200902.0,51048972.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,removed,removed,R,CC,200901.0,20588458.0,2,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,removed,removed,R,MLO,200901.0,20588510.0,2,2,NaN,X,NaN,NaN,2 micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,removed,removed,L,MLO,200901.0,20588536.0,2,5,X,X,NaN,NaN,nodulo QSE + micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,removed,removed,L,CC,200901.0,20588562.0,2,5,X,X,NaN,NaN,nodulo QSE + micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,removed,removed,R,CC,201001.0,22670809.0,1,4a,X,X,NaN,NaN,nódulo + micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,removed,removed,L,CC,201001.0,22670832.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,removed,removed,R,MLO,201001.0,22670855.0,1,5,X,X,NaN,NaN,nódulo + duas calcificações,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,removed,removed,L,MLO,201001.0,22670878.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,removed,removed,R,CC,200802.0,22678953.0,3,4a,NaN,X,NaN,NaN,microcalcificações QSE;Cluster,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,removed,removed,L,CC,200802.0,22678980.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,removed,removed,R,MLO,200802.0,22679008.0,3,4a,NaN,X,NaN,NaN,microcalcificações QSE;Cluster,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,removed,removed,L,MLO,200802.0,22679036.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,removed,removed,L,MLO,201001.0,50998413.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,removed,removed,R,MLO,201001.0,50998440.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,removed,removed,L,CC,201001.0,50998467.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,removed,removed,R,CC,201001.0,50998494.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,removed,removed,R,CC,200902.0,20587294.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,removed,removed,L,CC,200902.0,20587320.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,removed,removed,R,MLO,200902.0,20587346.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,removed,removed,L,MLO,200902.0,20587372.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,removed,removed,L,CC,200902.0,20587466.0,4,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,removed,removed,R,MLO,200902.0,20587492.0,4,2,NaN,X,NaN,NaN,micros,NaN,NaN,not possible,NaN,NaN,NaN,NaN,NaN,NaN
90,removed,removed,L,MLO,200902.0,20587518.0,4,2,NaN,X,NaN,NaN,micros,NaN,NaN,not possible,NaN,NaN,NaN,NaN,NaN,NaN
91,removed,removed,R,CC,200902.0,20587544.0,4,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,removed,removed,L,MLO,201001.0,50996201.0,4,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,removed,removed,L,CC,201001.0,50996228.0,4,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,removed,removed,L,MLO,201001.0,50993787.0,3,2,NaN,X,NaN,NaN,calcificações - follow up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,removed,removed,R,MLO,201001.0,50993814.0,3,2,NaN,X,NaN,NaN,calcificações,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,removed,removed,L,CC,201001.0,50993841.0,3,2,NaN,X,NaN,NaN,calcificações - follow up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,removed,removed,R,CC,201001.0,50993868.0,3,2,NaN,X,NaN,NaN,calcificações,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,removed,removed,L,MLO,200802.0,50993895.0,3,2,NaN,X,NaN,NaN,calcificações - follow up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,removed,removed,R,MLO,200802.0,50993922.0,3,2,NaN,X,NaN,NaN,calcificações,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,removed,removed,L,CC,200802.0,50993949.0,3,2,NaN,X,NaN,NaN,calcificações - follow up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,removed,removed,R,CC,200802.0,50993976.0,3,2,NaN,X,NaN,NaN,calcificações,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,removed,removed,R,CC,200901.0,22614353.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,removed,removed,L,CC,200901.0,22614379.0,1,5,X,X,NaN,NaN,nódulo + micro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,removed,removed,R,MLO,200901.0,22614405.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,removed,removed,L,MLO,200901.0,22614431.0,1,5,X,X,NaN,NaN,nódulo + micro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,removed,removed,L,MLO,201001.0,53587572.0,2,2,NaN,X,NaN,NaN,calcificações benignas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,removed,removed,L,CC,201001.0,53587599.0,2,2,NaN,X,NaN,NaN,calcificações benignas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,removed,removed,L,MLO,201001.0,50996800.0,2,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,removed,removed,R,MLO,201001.0,50996827.0,2,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,removed,removed,L,CC,201001.0,50996854.0,2,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,removed,removed,R,CC,201001.0,50996881.0,2,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,removed,removed,L,MLO,201001.0,50993399.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,removed,removed,L,CC,201001.0,50993426.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,removed,removed,R,CC,201001.0,27829134.0,1,5,X,X,NaN,NaN,nódulo;micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,removed,removed,L,CC,201001.0,27829161.0,1,1,NaN,NaN,NaN,NaN,normal,NaN,no annotation (normal),NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,removed,removed,R,MLO,201001.0,27829188.0,1,5,X,X,NaN,NaN,nódulo;micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,removed,removed,L,MLO,201001.0,27829215.0,1,1,NaN,NaN,NaN,NaN,normal,NaN,no annotation (normal),NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,removed,removed,L,MLO,201001.0,50997223.0,4,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,exemplo de onde se deve encontrar microcalcifi...,NaN,NaN,NaN,NaN,NaN
119,removed,removed,R,MLO,201001.0,50997250.0,4,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,removed,removed,L,CC,201001.0,50997277.0,4,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,removed,removed,R,CC,201001.0,50997304.0,4,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,removed,removed,R,CC,201001.0,22670442.0,2,1,NaN,NaN,NaN,NaN,normal,NaN,No annotation (Normal),NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,removed,removed,L,CC,201001.0,22670465.0,2,5,X,X,NaN,X,nódulo + micros - QSE; densidade + micros - qu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,removed,removed,R,MLO,201001.0,22670488.0,2,1,NaN,NaN,NaN,NaN,normal,NaN,No annotation (Normal),NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,removed,removed,L,MLO,201001.0,22670511.0,2,5,X,X,NaN,X,nódulo + micros - QSE; densidade + micros - qu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,removed,removed,L,MLO,201001.0,53581769.0,2,1,NaN,NaN,NaN,NaN,normal,NaN,No annotation (Normal),NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,removed,removed,L,CC,201001.0,53581796.0,2,1,NaN,NaN,NaN,NaN,normal,NaN,No annotation (Normal),NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,removed,removed,L,MLO,200901.0,24065530.0,4,4c,X,NaN,NaN,NaN,nódulo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,removed,removed,R,MLO,200901.0,24065557.0,4,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,removed,removed,L,CC,200901.0,24065584.0,4,4c,NaN,NaN,NaN,NaN,nódulo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,removed,removed,R,CC,200901.0,24065611.0,4,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,removed,removed,L,MLO,201001.0,53587104.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,removed,removed,L,CC,201001.0,53587131.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,removed,removed,R,CC,201001.0,30011484.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,removed,removed,L,CC,201001.0,30011507.0,1,4c,X,X,NaN,NaN,Nódulo QSI + micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,removed,removed,R,MLO,201001.0,30011530.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,removed,removed,L,MLO,201001.0,30011553.0,1,4c,X,X,NaN,NaN,Nódulo QSI + micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,removed,removed,L,MLO,200901.0,24055573.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,removed,removed,R,MLO,200901.0,24055600.0,3,4c,NaN,X,X,NaN,distorção QII,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,removed,removed,L,CC,200901.0,24055627.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,removed,removed,R,CC,200901.0,24055654.0,3,4c,NaN,X,X,NaN,distorção QII,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,removed,removed,L,MLO,200802.0,24065680.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,removed,removed,R,MLO,200802.0,24065707.0,1,5,X,X,NaN,NaN,nódulo QSE + micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,removed,removed,L,CC,200802.0,24065734.0,1,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,removed,removed,R,CC,200802.0,24065761.0,1,5,X,X,NaN,NaN,nódulo QSE + micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,removed,removed,L,MLO,200902.0,50999432.0,1,5,X,X,NaN,NaN,nodulo QSE + 1 micro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,removed,removed,L,CC,200902.0,50999459.0,1,5,X,NaN,NaN,NaN,nodulo QSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,removed,removed,R,MLO,200902.0,51048738.0,3,3,X,NaN,NaN,NaN,fibroadenoma QII,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,removed,removed,R,CC,200902.0,51048765.0,3,3,X,NaN,NaN,NaN,fibroadenoma QII,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,removed,removed,L,MLO,201001.0,50998177.0,3,2,NaN,X,NaN,NaN,calcificações,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,removed,removed,R,MLO,201001.0,50998204.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,removed,removed,L,CC,201001.0,50998231.0,3,2,NaN,X,NaN,NaN,2 calcificações,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,removed,removed,R,CC,201001.0,50998258.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,removed,removed,L,MLO,200902.0,20588308.0,4,3,X,NaN,NaN,NaN,nodulo QSI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,removed,removed,L,CC,200902.0,20588334.0,4,3,X,NaN,NaN,NaN,nodulo QSI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,removed,removed,R,CC,201001.0,22678787.0,3,2,X,X,NaN,NaN,nódulo + micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,removed,removed,L,CC,201001.0,22678810.0,3,2,NaN,X,NaN,NaN,micros - follow up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,removed,removed,R,MLO,201001.0,22678833.0,3,2,X,X,NaN,NaN,nódulo + micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,removed,removed,L,MLO,201001.0,22678856.0,3,2,NaN,X,NaN,NaN,micros - follow up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,removed,removed,R,CC,200901.0,22580341.0,3,2,X,X,NaN,NaN,macrocistos – nódulos + Micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,removed,removed,L,CC,200901.0,22580367.0,3,2,X,NaN,NaN,NaN,macrocistos - nódulos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,removed,removed,R,MLO,200901.0,22580393.0,3,2,X,X,NaN,NaN,macrocistos – nódulos + Micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163,removed,removed,L,MLO,200901.0,22580419.0,3,2,X,NaN,NaN,NaN,macrocistos - nódulos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,removed,removed,L,MLO,200901.0,24055149.0,3,5,NaN,X,NaN,NaN,micros;Cluster,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,removed,removed,R,MLO,200901.0,24055176.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,removed,removed,L,CC,200901.0,24055203.0,3,5,NaN,X,NaN,NaN,micros;Cluster,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,removed,removed,R,CC,200902.0,20587994.0,3,6,X,X,NaN,NaN,nódulo + uma micro;Spiculated Region,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,removed,removed,L,CC,200902.0,20588020.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,removed,removed,R,MLO,200902.0,20588046.0,3,6,X,X,NaN,NaN,Nódulo + uma micro; spiculated region,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,removed,removed,L,MLO,200902.0,20588072.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,removed,removed,R,CC,200902.0,26933772.0,3,2,NaN,X,NaN,NaN,micros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
INbreast[pd.isna(INbreast["File Name"])]

,Patient ID,Patient age,Laterality,View,Acquisition date,File Name,ACR,Bi-Rads,Mass,Micros,Distortion,Asymmetry,Findings Notes (in Portuguese),Other Notes,Lesion Annotation Status,Pectoral Muscle Annotation,Other Annotations,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
411,NaN,NaN,NaN,NaN,NaN,NaN,28,49,108,308,3,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:

# Normalizar columnas de lesión
def get_lesion_type(row):
    tipos = []

    # OJO: asegúrate de que los nombres de columnas están normalizados
    if pd.notna(row["Mass "]):        # o "Mass" si ya lo limpiaste
        tipos.append("MASS")
    if pd.notna(row["Micros"]):
        tipos.append("MICRO")
    if pd.notna(row["Distortion"]):
        tipos.append("DISTORTION")
    if pd.notna(row["Asymmetry"]):
        tipos.append("ASYMMETRY")

    if len(tipos) == 0:
        return "NONE"

    return "_".join(tipos)

INbreast["LesionType"] = INbreast.apply(get_lesion_type, axis=1)  #crea una nueva columna con los nombres 
print(INbreast.columns.tolist())

['Patient ID', 'Patient age', 'Laterality', 'View', 'Acquisition date', 'File Name', 'ACR', 'Bi-Rads', 'Mass ', 'Micros', 'Distortion', 'Asymmetry', 'Findings Notes (in Portuguese)', 'Other Notes', 'Lesion Annotation Status', 'Pectoral Muscle Annotation', 'Other Annotations', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'LesionType']

In [5]:
INbreast[pd.isna(INbreast["File Name"])]

,Patient ID,Patient age,Laterality,View,Acquisition date,File Name,ACR,Bi-Rads,Mass,Micros,Distortion,Asymmetry,Findings Notes (in Portuguese),Other Notes,Lesion Annotation Status,Pectoral Muscle Annotation,Other Annotations,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,LesionType
410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NONE
411,NaN,NaN,NaN,NaN,NaN,NaN,28,49,108,308,3,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MASS_MICRO_DISTORTION_ASYMMETRY

In [6]:
#Eliminamos las filas con NaN:
INbreast = INbreast[INbreast["File Name"].notna()].copy()

In [8]:
#Los nombres actuales empiezan con el filename. Así, solo tenemos que añadir los datos a la foto que 
#coincida con el filename
#Se añadirá el tipo de lesión y el bi-rads, que es como una clasificación subjetiva de la gravedad
import os
import pandas as pd

# === CONFIGURACIÓN ===
images_dir = "Imagenes mascaras segmentacion INbreast"  # carpeta donde están las imágenes originales
output_dir = "Imagenes mascaras segmentacion INbreast RENOMBRADAS"  
# carpeta donde guardarás las imágenes renombradas

def find_image_by_prefix(prefix, folder):
    """
    Busca el primer archivo en 'folder' cuyo nombre empiece por 'prefix'.
    Devuelve la ruta completa o None si no existe.
    """
    prefix = str(prefix)

    for fname in os.listdir(folder):
        if fname.startswith(prefix):
            return fname

    return None

os.makedirs(output_dir, exist_ok=True)



# === RENOMBRAR ===
for idx, row in INbreast.iterrows():

    # Nombre original del archivo (INbreast usa números tipo 205881)
    filename_dataset = str(int(row["File Name"]))
    original_name = find_image_by_prefix(filename_dataset, images_dir)

    try:
        original_path = os.path.join(images_dir, original_name)
    except:
        print(f"NO ENCONTRADO: {filename_dataset}")
        continue

    # Construir nuevo nombre
    lesion = row["LesionType"]
    birads = row['Bi-Rads']

    new_name = f"{lesion}_bi-rads_{birads}_{original_name}"
    new_path = os.path.join(output_dir, new_name)

    # copiar:
    import shutil
    original_path = os.path.join(images_dir, original_name)
   
    shutil.copy(original_path, new_path)
    print(f'imagen {original_name} renombrada', '\r')

print("Renombrado completado.")

NO ENCONTRADO: 22678622
imagen 22678646_61b13c59bcba149e_MG_L_CC_ANON_mask.png renombrada
NO ENCONTRADO: 22678670
imagen 22678694_61b13c59bcba149e_MG_L_ML_ANON_mask.png renombrada
imagen 22614074_6bd24a0a42c19ce1_MG_R_CC_ANON_mask.png renombrada
imagen 22614097_6bd24a0a42c19ce1_MG_L_CC_ANON_mask.png renombrada
imagen 22614127_6bd24a0a42c19ce1_MG_R_ML_ANON_mask.png renombrada
imagen 22614150_6bd24a0a42c19ce1_MG_L_ML_ANON_mask.png renombrada
imagen 50997434_97ec8cadfca70d32_MG_L_ML_ANON_mask.png renombrada
imagen 50997461_97ec8cadfca70d32_MG_R_ML_ANON_mask.png renombrada
imagen 50997488_97ec8cadfca70d32_MG_L_CC_ANON_mask.png renombrada
imagen 50997515_97ec8cadfca70d32_MG_R_CC_ANON_mask.png renombrada
imagen 24055445_ac3185e18ffdc7b6_MG_L_ML_ANON_mask.png renombrada
imagen 24055464_ac3185e18ffdc7b6_MG_R_ML_ANON_mask.png renombrada
imagen 24055483_ac3185e18ffdc7b6_MG_L_CC_ANON_mask.png renombrada
imagen 24055502_ac3185e18ffdc7b6_MG_R_CC_ANON_mask.png renombrada
imagen 22580192_5530d5782fc89dd7_MG_R_CC_ANON_mask.png renombrada
NO ENCONTRADO: 22580218
imagen 22580244_5530d5782fc89dd7_MG_R_ML_ANON_mask.png renombrada
NO ENCONTRADO: 22580270
imagen 50998032_66adfbb4f19c76d2_MG_R_CC_ANON_mask.png renombrada
imagen 50998059_66adfbb4f19c76d2_MG_L_ML_ANON_mask.png renombrada
imagen 50998086_66adfbb4f19c76d2_MG_R_ML_ANON_mask.png renombrada
imagen 50998113_66adfbb4f19c76d2_MG_L_CC_ANON_mask.png renombrada
imagen 50997742_cbb6c98a81e69eeb_MG_L_ML_ANON_mask.png renombrada
imagen 50997769_cbb6c98a81e69eeb_MG_R_ML_ANON_mask.png renombrada
imagen 50997796_cbb6c98a81e69eeb_MG_L_CC_ANON_mask.png renombrada
imagen 50997823_cbb6c98a81e69eeb_MG_R_CC_ANON_mask.png renombrada
imagen 22670620_e15a16f87b4f9782_MG_R_CC_ANON_mask.png renombrada
NO ENCONTRADO: 22670643
imagen 22670673_e15a16f87b4f9782_MG_R_ML_ANON_mask.png renombrada
NO ENCONTRADO: 22670703
NO ENCONTRADO: 53581379
imagen 53581406_b231a8ba4dd4214f_MG_R_ML_ANON_mask.png renombrada
NO ENCONTRADO: 53581433
imagen 53581460_b231a8ba4dd4214f_MG_R_CC_ANON_mask.png renombrada
imagen 24065833_c01f83a1eb283270_MG_L_ML_ANON_mask.png renombrada
imagen 24065860_c01f83a1eb283270_MG_R_ML_ANON_mask.png renombrada
imagen 24065887_c01f83a1eb283270_MG_L_CC_ANON_mask.png renombrada
imagen 24065914_c01f83a1eb283270_MG_R_CC_ANON_mask.png renombrada
imagen 24055877_839819f2eadaf325_MG_L_ML_ANON_mask.png renombrada
imagen 24055904_839819f2eadaf325_MG_R_ML_ANON_mask.png renombrada
imagen 24055931_839819f2eadaf325_MG_L_CC_ANON_mask.png renombrada
imagen 24055958_839819f2eadaf325_MG_R_CC_ANON_mask.png renombrada
imagen 53587427_d2befe622e188943_MG_L_ML_ANON_mask.png renombrada
imagen 53587454_d2befe622e188943_MG_R_ML_ANON_mask.png renombrada
imagen 53587481_d2befe622e188943_MG_L_CC_ANON_mask.png renombrada
imagen 53587508_d2befe622e188943_MG_R_CC_ANON_mask.png renombrada
imagen 51049462_6f64793857feb5d0_MG_L_ML_ANON_mask.png renombrada
imagen 51049489_6f64793857feb5d0_MG_R_ML_ANON_mask.png renombrada
imagen 51049516_6f64793857feb5d0_MG_L_CC_ANON_mask.png renombrada
imagen 51049543_6f64793857feb5d0_MG_R_CC_ANON_mask.png renombrada
imagen 51049628_6f64793857feb5d0_MG_L_ML_ANON_mask.png renombrada
imagen 51049655_6f64793857feb5d0_MG_R_ML_ANON_mask.png renombrada
imagen 51049682_6f64793857feb5d0_MG_L_CC_ANON_mask.png renombrada
imagen 51070197_6f64793857feb5d0_MG_R_CC_ANON_mask.png renombrada
imagen 53580611_40e22f2e3215b954_MG_L_ML_ANON_mask.png renombrada
imagen 53580638_40e22f2e3215b954_MG_R_ML_ANON_mask.png renombrada
imagen 53580665_40e22f2e3215b954_MG_L_CC_ANON_mask.png renombrada
imagen 53580692_40e22f2e3215b954_MG_R_CC_ANON_mask.png renombrada
imagen 53586960_809e3f43339f93c6_MG_L_ML_ANON_mask.png renombrada
imagen 53586987_809e3f43339f93c6_MG_R_ML_ANON_mask.png renombrada
imagen 53587014_809e3f43339f93c6_MG_L_CC_ANON_mask.png renombrada
imagen 53587041_809e3f43339f93c6_MG_R_CC_ANON_mask.png renombrada
imagen 51048891_f3e93e889a7746f0_MG_L_ML_ANON_mask.png renombrada
imagen 51048918_f3e93e889a7746f0_MG_R_ML_ANON_mask.png renombrada
imagen 51048945_f3e93e889a7746f0_MG_L_CC_ANON_mask.png renombrada
imagen 51048972_f3e93e889a7746f0_MG_R_CC_ANON_mask.png renombrada
imagen 20588458_bf1a6aaadb05e3df_MG_R_CC_ANON_mask.png renombrada
imagen 20588510_bf1a6aaadb05e3df_MG_R_ML_ANON_mask.png renombrada
imagen 20588536_bf1a6aaadb05e3df_MG_L_ML_ANON_mask.png renombrada
imagen 20588562_bf1a6aaadb05e3df_MG_L_CC_ANON_mask.png renombrada
imagen 22670809_0b7396cdccacca82_MG_R_CC_ANON_mask.png renombrada
imagen 22670832_0b7396cdccacca82_MG_L_CC_ANON_mask.png renombrada
imagen 22670855_0b7396cdccacca82_MG_R_ML_ANON_mask.png renombrada
imagen 22670878_0b7396cdccacca82_MG_L_ML_ANON_mask.png renombrada
imagen 22678953_b9a4da5f2dae63a9_MG_R_CC_ANON_mask.png renombrada
imagen 22678980_b9a4da5f2dae63a9_MG_L_CC_ANON_mask.png renombrada
imagen 22679008_b9a4da5f2dae63a9_MG_R_ML_ANON_mask.png renombrada
imagen 22679036_b9a4da5f2dae63a9_MG_L_ML_ANON_mask.png renombrada
imagen 50998413_1f139436acfc5467_MG_L_ML_ANON_mask.png renombrada
imagen 50998440_1f139436acfc5467_MG_R_ML_ANON_mask.png renombrada
imagen 50998467_1f139436acfc5467_MG_L_CC_ANON_mask.png renombrada
imagen 50998494_1f139436acfc5467_MG_R_CC_ANON_mask.png renombrada
imagen 20587294_e634830794f5c1bd_MG_R_CC_ANON_mask.png renombrada
imagen 20587320_e634830794f5c1bd_MG_L_CC_ANON_mask.png renombrada
imagen 20587346_e634830794f5c1bd_MG_R_ML_ANON_mask.png renombrada
imagen 20587372_e634830794f5c1bd_MG_L_ML_ANON_mask.png renombrada
imagen 20587466_d571b5880ad2a016_MG_L_CC_ANON_mask.png renombrada
imagen 20587492_d571b5880ad2a016_MG_R_ML_ANON_mask.png renombrada
imagen 20587518_d571b5880ad2a016_MG_L_ML_ANON_mask.png renombrada
imagen 20587544_d571b5880ad2a016_MG_R_CC_ANON_mask.png renombrada
imagen 50996201_8c1b2bd64ca4d778_MG_L_ML_ANON_mask.png renombrada
imagen 50996228_8c1b2bd64ca4d778_MG_L_CC_ANON_mask.png renombrada
imagen 50993787_de5e8d61e501a71b_MG_L_ML_ANON_mask.png renombrada
imagen 50993814_de5e8d61e501a71b_MG_R_ML_ANON_mask.png renombrada
imagen 50993841_de5e8d61e501a71b_MG_L_CC_ANON_mask.png renombrada
imagen 50993868_de5e8d61e501a71b_MG_R_CC_ANON_mask.png renombrada
imagen 50993895_de5e8d61e501a71b_MG_L_ML_ANON_mask.png renombrada
imagen 50993922_de5e8d61e501a71b_MG_R_ML_ANON_mask.png renombrada
imagen 50993949_de5e8d61e501a71b_MG_L_CC_ANON_mask.png renombrada
imagen 50993976_de5e8d61e501a71b_MG_R_CC_ANON_mask.png renombrada
imagen 22614353_d065adcb9905b973_MG_R_CC_ANON_mask.png renombrada
imagen 22614379_d065adcb9905b973_MG_L_CC_ANON_mask.png renombrada
imagen 22614405_d065adcb9905b973_MG_R_ML_ANON_mask.png renombrada
imagen 22614431_d065adcb9905b973_MG_L_ML_ANON_mask.png renombrada
imagen 53587572_11e6732579acf692_MG_L_ML_ANON_mask.png renombrada
imagen 53587599_11e6732579acf692_MG_L_CC_ANON_mask.png renombrada
imagen 50996800_fdf4a1516f88b280_MG_L_ML_ANON_mask.png renombrada
imagen 50996827_fdf4a1516f88b280_MG_R_ML_ANON_mask.png renombrada
imagen 50996854_fdf4a1516f88b280_MG_L_CC_ANON_mask.png renombrada
imagen 50996881_fdf4a1516f88b280_MG_R_CC_ANON_mask.png renombrada
imagen 50993399_5d85ecc9cf26b254_MG_L_ML_ANON_mask.png renombrada
imagen 50993426_5d85ecc9cf26b254_MG_L_CC_ANON_mask.png renombrada
imagen 27829134_fbb55bf7fff48540_MG_R_CC_ANON_mask.png renombrada
NO ENCONTRADO: 27829161
imagen 27829188_fbb55bf7fff48540_MG_R_ML_ANON_mask.png renombrada
NO ENCONTRADO: 27829215
imagen 50997223_9054942f7be52dd9_MG_L_ML_ANON_mask.png renombrada
imagen 50997250_9054942f7be52dd9_MG_R_ML_ANON_mask.png renombrada
imagen 50997277_9054942f7be52dd9_MG_L_CC_ANON_mask.png renombrada
imagen 50997304_9054942f7be52dd9_MG_R_CC_ANON_mask.png renombrada
NO ENCONTRADO: 22670442
imagen 22670465_7e677f3d530e41ed_MG_L_CC_ANON_mask.png renombrada
NO ENCONTRADO: 22670488
imagen 22670511_7e677f3d530e41ed_MG_L_ML_ANON_mask.png renombrada
NO ENCONTRADO: 53581769
NO ENCONTRADO: 53581796
imagen 24065530_d8205a09c8173f44_MG_L_ML_ANON_mask.png renombrada
imagen 24065557_d8205a09c8173f44_MG_R_ML_ANON_mask.png renombrada
imagen 24065584_d8205a09c8173f44_MG_L_CC_ANON_mask.png renombrada
imagen 24065611_d8205a09c8173f44_MG_R_CC_ANON_mask.png renombrada
imagen 53587104_7b71aa9928e6975e_MG_L_ML_ANON_mask.png renombrada
imagen 53587131_7b71aa9928e6975e_MG_L_CC_ANON_mask.png renombrada
imagen 30011484_349323117bf0fd93_MG_R_CC_ANON_mask.png renombrada
imagen 30011507_349323117bf0fd93_MG_L_CC_ANON_mask.png renombrada
imagen 30011530_349323117bf0fd93_MG_R_ML_ANON_mask.png renombrada
imagen 30011553_349323117bf0fd93_MG_L_ML_ANON_mask.png renombrada
imagen 24055573_6f1aef40b3775182_MG_L_ML_ANON_mask.png renombrada
imagen 24055600_6f1aef40b3775182_MG_R_ML_ANON_mask.png renombrada
imagen 24055627_6f1aef40b3775182_MG_L_CC_ANON_mask.png renombrada
imagen 24055654_6f1aef40b3775182_MG_R_CC_ANON_mask.png renombrada
imagen 24065680_5291e1aee2bbf5df_MG_L_ML_ANON_mask.png renombrada
imagen 24065707_5291e1aee2bbf5df_MG_R_ML_ANON_mask.png renombrada
imagen 24065734_5291e1aee2bbf5df_MG_L_CC_ANON_mask.png renombrada
imagen 24065761_5291e1aee2bbf5df_MG_R_CC_ANON_mask.png renombrada
imagen 50999432_f62fbf38fb208316_MG_L_ML_ANON_mask.png renombrada
imagen 50999459_f62fbf38fb208316_MG_L_CC_ANON_mask.png renombrada
imagen 51048738_3f22cdda8da215e3_MG_R_ML_ANON_mask.png renombrada
imagen 51048765_3f22cdda8da215e3_MG_R_CC_ANON_mask.png renombrada
imagen 50998177_f34ee0ab6591b792_MG_L_ML_ANON_mask.png renombrada
imagen 50998204_f34ee0ab6591b792_MG_R_ML_ANON_mask.png renombrada
imagen 50998231_f34ee0ab6591b792_MG_L_CC_ANON_mask.png renombrada
imagen 50998258_f34ee0ab6591b792_MG_R_CC_ANON_mask.png renombrada
imagen 20588308_493155e17143edef_MG_L_ML_ANON_mask.png renombrada
imagen 20588334_493155e17143edef_MG_L_CC_ANON_mask.png renombrada
imagen 22678787_64a22c47765f0c5c_MG_R_CC_ANON_mask.png renombrada
imagen 22678810_64a22c47765f0c5c_MG_L_CC_ANON_mask.png renombrada
imagen 22678833_64a22c47765f0c5c_MG_R_ML_ANON_mask.png renombrada
imagen 22678856_64a22c47765f0c5c_MG_L_ML_ANON_mask.png renombrada
imagen 22580341_5eae9beae14d26fd_MG_R_CC_ANON_mask.png renombrada
imagen 22580367_5eae9beae14d26fd_MG_L_CC_ANON_mask.png renombrada
imagen 22580393_5eae9beae14d26fd_MG_R_ML_ANON_mask.png renombrada
imagen 22580419_5eae9beae14d26fd_MG_L_ML_ANON_mask.png renombrada
imagen 24055149_606e9b184978a350_MG_L_ML_ANON_mask.png renombrada
imagen 24055176_606e9b184978a350_MG_R_ML_ANON_mask.png renombrada
imagen 24055203_606e9b184978a350_MG_L_CC_ANON_mask.png renombrada
imagen 20587994_024ee3569b2605dc_MG_R_CC_ANON_mask.png renombrada
imagen 20588020_024ee3569b2605dc_MG_L_CC_ANON_mask.png renombrada
imagen 20588046_024ee3569b2605dc_MG_R_ML_ANON_mask.png renombrada
imagen 20588072_024ee3569b2605dc_MG_L_ML_ANON_mask.png renombrada
imagen 26933772_f8bfddc28e8045c0_MG_R_CC_ANON_mask.png renombrada
imagen 26933801_f8bfddc28e8045c0_MG_L_CC_ANON_mask.png renombrada
imagen 26933830_f8bfddc28e8045c0_MG_R_ML_ANON_mask.png renombrada
imagen 26933859_f8bfddc28e8045c0_MG_L_ML_ANON_mask.png renombrada
imagen 50995762_0c735e8768d276b4_MG_R_ML_ANON_mask.png renombrada
imagen 50995789_0c735e8768d276b4_MG_R_CC_ANON_mask.png renombrada
imagen 22670278_98429c0bdf78c0c7_MG_R_CC_ANON_mask.png renombrada
imagen 22670301_98429c0bdf78c0c7_MG_L_CC_ANON_mask.png renombrada
imagen 22670324_98429c0bdf78c0c7_MG_R_ML_ANON_mask.png renombrada
imagen 22670347_98429c0bdf78c0c7_MG_L_ML_ANON_mask.png renombrada
NO ENCONTRADO: 53582540
NO ENCONTRADO: 53582567
imagen 22427682_d713ef5849f98b6c_MG_R_CC_ANON_mask.png renombrada
imagen 22427705_d713ef5849f98b6c_MG_L_CC_ANON_mask.png renombrada
imagen 22427728_d713ef5849f98b6c_MG_R_ML_ANON_mask.png renombrada
imagen 22427751_d713ef5849f98b6c_MG_L_ML_ANON_mask.png renombrada
imagen 22613624_dcafa6ba6374ec07_MG_R_CC_ANON_mask.png renombrada
imagen 22613650_dcafa6ba6374ec07_MG_L_CC_ANON_mask.png renombrada
imagen 22613676_dcafa6ba6374ec07_MG_R_ML_ANON_mask.png renombrada
imagen 22613702_dcafa6ba6374ec07_MG_L_ML_ANON_mask.png renombrada
imagen 24055274_1e10aef17c9fe149_MG_L_ML_ANON_mask.png renombrada
imagen 24055328_1e10aef17c9fe149_MG_R_ML_ANON_mask.png renombrada
imagen 24055355_1e10aef17c9fe149_MG_L_CC_ANON_mask.png renombrada
imagen 24055382_1e10aef17c9fe149_MG_R_CC_ANON_mask.png renombrada
NO ENCONTRADO: 53586361
NO ENCONTRADO: 53586388
NO ENCONTRADO: 53586415
NO ENCONTRADO: 53586442
imagen 30011647_6968748e66837bc7_MG_R_CC_ANON_mask.png renombrada
imagen 30011674_6968748e66837bc7_MG_L_CC_ANON_mask.png renombrada
imagen 30011700_6968748e66837bc7_MG_R_ML_ANON_mask.png renombrada
imagen 30011727_6968748e66837bc7_MG_L_ML_ANON_mask.png renombrada
NO ENCONTRADO: 53581860
imagen 53581887_21e6cc12630e5e9f_MG_R_ML_ANON_mask.png renombrada
NO ENCONTRADO: 53581914
imagen 53581941_21e6cc12630e5e9f_MG_R_CC_ANON_mask.png renombrada
NO ENCONTRADO: 20588138
NO ENCONTRADO: 20588164
imagen 20588190_8d0b9620c53c0268_MG_L_CC_ANON_mask.png renombrada
imagen 20588216_8d0b9620c53c0268_MG_L_ML_ANON_mask.png renombrada
imagen 50996945_ce5e5e18a261cd29_MG_L_ML_ANON_mask.png renombrada
imagen 50996972_ce5e5e18a261cd29_MG_R_ML_ANON_mask.png renombrada
imagen 50996999_ce5e5e18a261cd29_MG_L_CC_ANON_mask.png renombrada
imagen 50997026_ce5e5e18a261cd29_MG_R_CC_ANON_mask.png renombrada
NO ENCONTRADO: 50997053
NO ENCONTRADO: 50997080
imagen 50997107_ce5e5e18a261cd29_MG_R_ML_ANON_mask.png renombrada
imagen 50997134_ce5e5e18a261cd29_MG_R_CC_ANON_mask.png renombrada
imagen 20587758_81cd83d2f4d78528_MG_L_CC_ANON_mask.png renombrada
imagen 20587784_81cd83d2f4d78528_MG_R_ML_ANON_mask.png renombrada
imagen 20587810_81cd83d2f4d78528_MG_L_ML_ANON_mask.png renombrada
imagen 20587836_81cd83d2f4d78528_MG_R_CC_ANON_mask.png renombrada
imagen 50996056_71c1a60d57c5322f_MG_L_ML_ANON_mask.png renombrada
imagen 50996083_71c1a60d57c5322f_MG_R_ML_ANON_mask.png renombrada
imagen 50996110_71c1a60d57c5322f_MG_L_CC_ANON_mask.png renombrada
imagen 50996137_71c1a60d57c5322f_MG_R_CC_ANON_mask.png renombrada
NO ENCONTRADO: 53582395
imagen 53582422_3f0db31711fc9795_MG_R_ML_ANON_mask.png renombrada
NO ENCONTRADO: 53582449
imagen 53582476_3f0db31711fc9795_MG_R_CC_ANON_mask.png renombrada
imagen 50999094_cb65e8dac169f596_MG_L_ML_ANON_mask.png renombrada
NO ENCONTRADO: 50999121
imagen 50999148_cb65e8dac169f596_MG_L_CC_ANON_mask.png renombrada
NO ENCONTRADO: 50999175
imagen 50999246_cb65e8dac169f596_MG_L_ML_ANON_mask.png renombrada
NO ENCONTRADO: 50999273
imagen 50999300_cb65e8dac169f596_MG_L_CC_ANON_mask.png renombrada
NO ENCONTRADO: 50999327
imagen 50994535_de4c34099d6ef8de_MG_R_ML_ANON_mask.png renombrada
imagen 50994562_de4c34099d6ef8de_MG_R_CC_ANON_mask.png renombrada
imagen 50994589_de4c34099d6ef8de_MG_R_ML_ANON_mask.png renombrada
imagen 50994616_de4c34099d6ef8de_MG_R_CC_ANON_mask.png renombrada
imagen 22427840_bbd6a3a35438c11b_MG_R_CC_ANON_mask.png renombrada
imagen 22427864_bbd6a3a35438c11b_MG_L_CC_ANON_mask.png renombrada
imagen 22579730_bbd6a3a35438c11b_MG_R_ML_ANON_mask.png renombrada
imagen 22579754_bbd6a3a35438c11b_MG_L_ML_ANON_mask.png renombrada
imagen 30011798_4f20c1285d8f0b1f_MG_R_CC_ANON_mask.png renombrada
imagen 30011824_4f20c1285d8f0b1f_MG_L_CC_ANON_mask.png renombrada
imagen 30011850_4f20c1285d8f0b1f_MG_R_ML_ANON_mask.png renombrada
imagen 30318067_4f20c1285d8f0b1f_MG_L_ML_ANON_mask.png renombrada
imagen 50996709_330e5fe16929eed4_MG_R_ML_ANON_mask.png renombrada
imagen 50996736_330e5fe16929eed4_MG_R_CC_ANON_mask.png renombrada
imagen 51049053_8c105bb715bf1c3c_MG_L_ML_ANON_mask.png renombrada
imagen 51049080_8c105bb715bf1c3c_MG_R_ML_ANON_mask.png renombrada
imagen 51049107_8c105bb715bf1c3c_MG_L_CC_ANON_mask.png renombrada
imagen 51049134_8c105bb715bf1c3c_MG_R_CC_ANON_mask.png renombrada
imagen 22614236_1e5c3af078f74b05_MG_L_CC_ANON_mask.png renombrada
imagen 22614266_1e5c3af078f74b05_MG_L_ML_ANON_mask.png renombrada
NO ENCONTRADO: 50994706
NO ENCONTRADO: 50994733
NO ENCONTRADO: 50994760
NO ENCONTRADO: 50994787
NO ENCONTRADO: 50994814
imagen 50994841_069212ec65a94339_MG_R_ML_ANON_mask.png renombrada
NO ENCONTRADO: 50994868
imagen 50994895_069212ec65a94339_MG_R_CC_ANON_mask.png renombrada
imagen 53586724_e5f3f68b9ce31228_MG_L_ML_ANON_mask.png renombrada
imagen 53586751_e5f3f68b9ce31228_MG_R_ML_ANON_mask.png renombrada
imagen 53586778_e5f3f68b9ce31228_MG_L_CC_ANON_mask.png renombrada
imagen 53586805_e5f3f68b9ce31228_MG_R_CC_ANON_mask.png renombrada
imagen 22614499_2dec4948fbe6336d_MG_R_CC_ANON_mask.png renombrada
imagen 22614522_2dec4948fbe6336d_MG_L_CC_ANON_mask.png renombrada
imagen 22614545_2dec4948fbe6336d_MG_R_ML_ANON_mask.png renombrada
imagen 22614568_2dec4948fbe6336d_MG_L_ML_ANON_mask.png renombrada
imagen 51049249_832ebce700241036_MG_L_CC_ANON_mask.png renombrada
imagen 51049276_832ebce700241036_MG_L_ML_ANON_mask.png renombrada
imagen 24058660_9e8db9e34d5275ef_MG_R_CC_ANON_mask.png renombrada
imagen 24058686_9e8db9e34d5275ef_MG_L_CC_ANON_mask.png renombrada
imagen 24058712_9e8db9e34d5275ef_MG_R_ML_ANON_mask.png renombrada
imagen 24058738_9e8db9e34d5275ef_MG_L_ML_ANON_mask.png renombrada
imagen 22613918_f23fa352e7de3dc7_MG_R_CC_ANON_mask.png renombrada
NO ENCONTRADO: 22613944
imagen 22613970_f23fa352e7de3dc7_MG_R_ML_ANON_mask.png renombrada
NO ENCONTRADO: 22613996
imagen 53580804_51bec6477a7898b9_MG_L_ML_ANON_mask.png renombrada
imagen 53580831_51bec6477a7898b9_MG_R_ML_ANON_mask.png renombrada
imagen 53580858_51bec6477a7898b9_MG_L_CC_ANON_mask.png renombrada
imagen 53580885_51bec6477a7898b9_MG_R_CC_ANON_mask.png renombrada
imagen 20587612_f4b2d377f43ba0bd_MG_R_CC_ANON_mask.png renombrada
imagen 20587638_f4b2d377f43ba0bd_MG_L_CC_ANON_mask.png renombrada
imagen 20587664_f4b2d377f43ba0bd_MG_R_ML_ANON_mask.png renombrada
imagen 20587690_f4b2d377f43ba0bd_MG_L_ML_ANON_mask.png renombrada
imagen 24065380_83db89f57aea498a_MG_L_ML_ANON_mask.png renombrada
imagen 24065407_83db89f57aea498a_MG_R_ML_ANON_mask.png renombrada
imagen 24065434_83db89f57aea498a_MG_L_CC_ANON_mask.png renombrada
imagen 24065461_83db89f57aea498a_MG_R_CC_ANON_mask.png renombrada
NO ENCONTRADO: 53581237
NO ENCONTRADO: 53581264
imagen 22670094_e1f51192f7bf3f5f_MG_R_CC_ANON_mask.png renombrada
imagen 22670124_e1f51192f7bf3f5f_MG_L_CC_ANON_mask.png renombrada
imagen 22670147_e1f51192f7bf3f5f_MG_R_ML_ANON_mask.png renombrada
imagen 22670177_e1f51192f7bf3f5f_MG_L_ML_ANON_mask.png renombrada
imagen 50993616_b03f1dd34eb3c55f_MG_L_ML_ANON_mask.png renombrada
imagen 50993643_b03f1dd34eb3c55f_MG_L_CC_ANON_mask.png renombrada
imagen 50993670_b03f1dd34eb3c55f_MG_L_ML_ANON_mask.png renombrada
imagen 50993697_b03f1dd34eb3c55f_MG_L_CC_ANON_mask.png renombrada
imagen 20587148_fd746d25eb40b3dc_MG_R_CC_ANON_mask.png renombrada
imagen 20587174_fd746d25eb40b3dc_MG_L_CC_ANON_mask.png renombrada
imagen 20587200_fd746d25eb40b3dc_MG_R_ML_ANON_mask.png renombrada
imagen 20587226_fd746d25eb40b3dc_MG_L_ML_ANON_mask.png renombrada
imagen 22580492_2a5b932da4ce5ca1_MG_R_CC_ANON_mask.png renombrada
imagen 22580520_2a5b932da4ce5ca1_MG_L_CC_ANON_mask.png renombrada
imagen 22580548_2a5b932da4ce5ca1_MG_R_ML_ANON_mask.png renombrada
imagen 22580576_2a5b932da4ce5ca1_MG_L_ML_ANON_mask.png renombrada
imagen 22579847_301f1776aebbf5d2_MG_R_CC_ANON_mask.png renombrada
imagen 22579870_301f1776aebbf5d2_MG_L_CC_ANON_mask.png renombrada
imagen 22579893_301f1776aebbf5d2_MG_R_ML_ANON_mask.png renombrada
imagen 22579916_301f1776aebbf5d2_MG_L_ML_ANON_mask.png renombrada
imagen 53582656_465aa5ec1b59efc6_MG_L_ML_ANON_mask.png renombrada
imagen 53582683_465aa5ec1b59efc6_MG_L_CC_ANON_mask.png renombrada
imagen 53582710_465aa5ec1b59efc6_MG_R_ML_ANON_mask.png renombrada
imagen 53582737_465aa5ec1b59efc6_MG_L_ML_ANON_mask.png renombrada
imagen 53582764_465aa5ec1b59efc6_MG_R_ML_ANON_mask.png renombrada
imagen 53582791_465aa5ec1b59efc6_MG_L_CC_ANON_mask.png renombrada
imagen 53582818_465aa5ec1b59efc6_MG_R_CC_ANON_mask.png renombrada
imagen 22670978_f571fd4e63c718e3_MG_L_CC_ANON_mask.png renombrada
imagen 22671003_f571fd4e63c718e3_MG_L_ML_ANON_mask.png renombrada
NO ENCONTRADO: 53582304
NO ENCONTRADO: 53582331
imagen 20586908_6c613a14b80a8591_MG_R_CC_ANON_mask.png renombrada