El dataset CBIS-DDSM incluye imágenes jpeg, un csv con la información clínica de la lesión, ROI y bounding boxes actualizados (vienen ya las coordenadas de la lesión, si hubiera).

La estructura del dataset es una carpeta con cierto nombre, que es un ID llamado StudyInstanceUID (DICOM). En esa carpeta hay una o varias jpegs.

Los csv pueden contener el patient_id, el image_file_path, y datos como el abnormality_type, pathology, o las coordenadas de la región de interés ROI. También puede traer la ruta relativa del jpeg al que hace referencia. 

Cada paciente tiene varios patient-ID (importante). Debemos tener en cuenta qué fotos son de cada paciente para no usar el mismo paciente en training y en testing.

In [1]:
#Primero habrá que sacar y entender los csv:
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)


df1 = pd.read_csv('calc_case_description_test_set.csv')
df1

,patient_id,breast density,left or right breast,image view,abnormality id,abnormality type,calc type,calc distribution,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path
0,P_00038,2,LEFT,CC,1,calcification,PUNCTATE-PLEOMORPHIC,CLUSTERED,4,BENIGN,2,Calc-Test_P_00038_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.85935434310203356712688695661986996009/1.3.6.1.4.1.9590.100.1.2.374115997511889073021386151921807063992/000000.dcm,Calc-Test_P_00038_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.161465562211359959230647609981488894942/1.3.6.1.4.1.9590.100.1.2.419081637812053404913157930753972718515/000001.dcm\n,Calc-Test_P_00038_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.161465562211359959230647609981488894942/1.3.6.1.4.1.9590.100.1.2.419081637812053404913157930753972718515/000000.dcm
1,P_00038,2,LEFT,MLO,1,calcification,PUNCTATE-PLEOMORPHIC,CLUSTERED,4,BENIGN,2,Calc-Test_P_00038_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.384159464510350889125645400702639717613/1.3.6.1.4.1.9590.100.1.2.174390361112646747718661211471328897934/000000.dcm,Calc-Test_P_00038_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.29112199613143138535387754440942211739/1.3.6.1.4.1.9590.100.1.2.188613955710170417803011787532523988680/000001.dcm\n,Calc-Test_P_00038_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.29112199613143138535387754440942211739/1.3.6.1.4.1.9590.100.1.2.188613955710170417803011787532523988680/000000.dcm
2,P_00038,2,RIGHT,CC,1,calcification,VASCULAR,NaN,2,BENIGN_WITHOUT_CALLBACK,5,Calc-Test_P_00038_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.177706148911820252341905176394069228468/1.3.6.1.4.1.9590.100.1.2.263861248711313923336051913560309963304/000000.dcm,Calc-Test_P_00038_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.200764632211227648028305709420627883105/1.3.6.1.4.1.9590.100.1.2.244876997513875090239564803900035037851/000001.dcm\n,Calc-Test_P_00038_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.200764632211227648028305709420627883105/1.3.6.1.4.1.9590.100.1.2.244876997513875090239564803900035037851/000000.dcm
3,P_00038,2,RIGHT,CC,2,calcification,VASCULAR,NaN,2,BENIGN_WITHOUT_CALLBACK,5,Calc-Test_P_00038_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.177706148911820252341905176394069228468/1.3.6.1.4.1.9590.100.1.2.263861248711313923336051913560309963304/000000.dcm,Calc-Test_P_00038_RIGHT_CC_2/1.3.6.1.4.1.9590.100.1.2.248538452013626298441249276382187367143/1.3.6.1.4.1.9590.100.1.2.360550081712464813321995483083632007570/000001.dcm\n,Calc-Test_P_00038_RIGHT_CC_2/1.3.6.1.4.1.9590.100.1.2.248538452013626298441249276382187367143/1.3.6.1.4.1.9590.100.1.2.360550081712464813321995483083632007570/000000.dcm
4,P_00038,2,RIGHT,MLO,1,calcification,VASCULAR,NaN,2,BENIGN_WITHOUT_CALLBACK,5,Calc-Test_P_00038_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.328421320411501709324953698601549885215/1.3.6.1.4.1.9590.100.1.2.44262460211112930513355519060642708846/000000.dcm,Calc-Test_P_00038_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.348569460311013218440657632223354965172/1.3.6.1.4.1.9590.100.1.2.126295284812046209819441424913058621714/000001.dcm\n,Calc-Test_P_00038_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.348569460311013218440657632223354965172/1.3.6.1.4.1.9590.100.1.2.126295284812046209819441424913058621714/000000.dcm
5,P_00038,2,RIGHT,MLO,2,calcification,VASCULAR,NaN,2,BENIGN_WITHOUT_CALLBACK,5,Calc-Test_P_00038_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.328421320411501709324953698601549885215/1.3.6.1.4.1.9590.100.1.2.44262460211112930513355519060642708846/000000.dcm,Calc-Test_P_00038_RIGHT_MLO_2/1.3.6.1.4.1.9590.100.1.2.57362695012780927721008884783926968463/1.3.6.1.4.1.9590.100.1.2.326152312412979080929913875463824504551/000001.dcm\n,Calc-Test_P_00038_RIGHT_MLO_2/1.3.6.1.4.1.9590.100.1.2.57362695012780927721008884783926968463/1.3.6.1.4.1.9590.100.1.2.326152312412979080929913875463824504551/000000.dcm
6,P_00041,1,LEFT,CC,2,calcification,LUCENT_CENTER,NaN,2,BENIGN_WITHOUT_CALLBACK,5,Calc-Test_P_00041_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.69692063913639875309068650720468252275/1.3.6.1.4.1.9590.100.1.2.272917492411709393015036949944104292812/000000.dcm,Calc-Test_P_00041_LEFT_CC_2/1.3.6.1.4.1.9590.100.1.2.261142802012312819739743387111814412775/1.3.6.1.4.1.9590.100.1.2.417988901712931471839803048043949179220/000001.dcm\n,Calc-Test_P_00041_LEFT_CC_2/1.3.6.1.4.1.9590.100.1.2.261142802012312819739743387111814412775/1.3.6.1.4.1.9590.100.1.2.417988901712931471839803048043949179220/000000.dcm
7,P_00041,1,LEFT,MLO,2,calcification,LUCENT_CENTER,NaN,2,BENIGN_WITHOUT_CALLBACK,5,Calc-Test_P_00041_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.142141008410911067722208613271583980130/1.3.6.1.4.1.9590.100.1.2.214716350711587846302171252931002081387/000000.dcm,Calc-Test_P_00041_LEFT_MLO_2/1.3.6.1.4.1.9590.100.1.2.372962290011068589008332414733650487987/1.3.6.1.4.1.9590.100.1.2.399466258212646932018425683324156637601/000001.dcm\n,Calc-Test_P_00041_LEFT_MLO_2/1.3.6.1.4.1.9590.100.1.2.372962290011068589008332414733650487987/1.3.6.1.4.1.9590.100.1.2.399466258212646932018425683324156637601/000000.dcm
8,P_00077,2,LEFT,CC,1,calcification,ROUND_AND_REGULAR,NaN,2,BENIGN_WITHOUT_CALLBACK,3,Calc-Test_P_00077_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.171237778213286314004831596800955774428/1.3.6.1.4.1.9590.100.1.2.120762895113344405411143779050723940544/000000.dcm,Calc-Test_P_00077_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.169810086012222817116620676350914651179/1.3.6.1.4.1.9590.100.1.2.290902692212797420812472702834030958061/000001.dcm\n,Calc-Test_P_00077_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.169810086012222817116620676350914651179/1.3.6.1.4.1.9590.100.1.2.290902692212797420812472702834030958061/000000.dcm
9,P_00077,2,LEFT,MLO,1,calcification,ROUND_AND_REGULAR,NaN,2,BENIGN_WITHOUT_CALLBACK,3,Calc-Test_P_00077_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.183241556612565531802314594842720002297/1.3.6.1.4.1.9590.100.1.2.69721320913248429509817283852233561951/000000.dcm,Calc-Test_P_00077_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.73175700011214399933783883971096330370/1.3.6.1.4.1.9590.100.1.2.367831870411922811139425611690829800810/000001.dcm\n,Calc-Test_P_00077_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.73175700011214399933783883971096330370/1.3.6.1.4.1.9590.100.1.2.367831870411922811139425611690829800810/000000.dcm
10,P_00077,2,RIGHT,CC,1,calcification,PUNCTATE,NaN,2,BENIGN_WITHOUT_CALLBACK,3,Calc-Test_P_00077_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.15129196611219884010077462182303438195/1.3.6.1.4.1.9590.100.1.2.267340905912306939309266861160349187486/000000.dcm,Calc-Test_P_00077_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.128598338712578310233468865791024171287/1.3.6.1.4.1.9590.100.1.2.18120839111604166536715296270446318790/000001.dcm\n,Calc-Test_P_00077_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.128598338712578310233468865791024171287/1.3.6.1.4.1.9590.100.1.2.18120839111604166536715296270446318790/000000.dcm
11,P_00077,2,RIGHT,CC,2,calcification,EGGSHELL,NaN,2,BENIGN_WITHOUT_CALLBACK,4,Calc-Test_P_00077_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.15129196611219884010077462182303438195/1.3.6.1.4.1.9590.100.1.2.267340905912306939309266861160349187486/000000.dcm,Calc-Test_P_00077_RIGHT_CC_2/1.3.6.1.4.1.9590.100.1.2.240816389213530863100640710652565160570/1.3.6.1.4.1.9590.100.1.2.267337645212125348116045687560822845214/000001.dcm\n,Calc-Test_P_00077_RIGHT_CC_2/1.3.6.1.4.1.9590.100.1.2.240816389213530863100640710652565160570/1.3.6.1.4.1.9590.100.1.2.267337645212125348116045687560822845214/000000.dcm
12,P_00077,2,RIGHT,MLO,1,calcification,EGGSHELL,NaN,2,BENIGN_WITHOUT_CALLBACK,4,Calc-Test_P_00077_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.365452443811764926000393384013009629026/1.3.6.1.4.1.9590.100.1.2.385318920211943956428747846422015934212/000000.dcm,Calc-Test_P_00077_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.16349096912810354232637881793856153896/1.3.6.1.4.1.9590.100.1.2.2973937511197802335272669830658543735/000001.dcm\n,Calc-Test_P_00077_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.16349096912810354232637881793856153896/1.3.6.1.4.1.9590.100.1.2.2973937511197802335272669830658543735/000000.dcm
13,P_00077,2,RIGHT,MLO,2,calcification,PUNCTATE,NaN,2,BENIGN_WITHOUT_CALLBACK,3,Calc-Test_P_00077_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.365452443811764926000393384013009629026/1.3.6.1.4.1.9590.100.1.2.385318920211943956428747846422015934212/000000.dcm,Calc-Test_P_00077_RIGHT_MLO_2/1.3.6.1.4.1.9590.100.1.2.201293926012476700233510716540615969496/1.3.6.1.4.1.9590.100.1.2.158000665111936457715619250084031698617/000001.dcm\n,Calc-Test_P_00077_RIGHT_MLO_2/1.3.6.1.4.1.9590.100.1.2.201293926012476700233510716540615969496/1.3.6.1.4.1.9590.100.1.2.158000665111936457715619250084031698617/000000.dcm
14,P_00100,4,RIGHT,CC,1,calcification,PLEOMORPHIC,CLUSTERED,4,BENIGN,4,Calc-Test_P_00100_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.230778565512681440620732773312948799985/1.3.6.1.4.1.9590.100.1.2.153667468610757963111534821171489110348/000000.dcm,Calc-Test_P_00100_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.207198724713893842216305292043033029651/1.3.6.1.4.1.9590.100.1.2.416175242512972515029128682820201897035/000001.dcm\n,Calc-Test_P_00100_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.207198724713893842216305292043033029651/1.3.6.1.4.1.9590.100.1.2.416175242512972515029128682820201897035/000000.dcm
15,P_00100,4,RIGHT,MLO,1,calcification,PLEOMORPHIC,CLUSTERED,4,BENIGN,4,Calc-Test_P_00100_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.261621815911957508608887658251980280242/1.3.6.1.4.1.9590.100.1.2.15995324612513297805389764184183861099/000000.dcm,Calc-Test_P_00100_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.250557415613561036623963340123165616849/1.3.6.1.4.1.9590.100.1.2.304205501811264755442623318170888604668/000001.dcm\n,Calc-Test_P_00100_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.250557415613561036623963340123165616849/1.3.6.1.4.1.9590.100.1.2.304205501811264755442623318170888604668/000000.dcm
16,P_00127,2,RIGHT,CC,1,calcification,PLEOMORPHIC,CLUSTERED,4,MALIGNANT,3,Calc-Test_P_00127_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.238227987212757626039739516193166448220/1.3.6.1.4.1.9590.100.1.2.61347581410432668240174563181885281950/000000.dcm,Calc-Test_P_00127_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.80182803312797292012070941550912613321/1.3.6.1.4.1.9590.100.1.2.2842079811478456724840697622497217059/000001.dcm\n,Calc-Test_P_00127_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.80182803312797292012070941550912613321/1.3.6.1.4.1.9590.100.1.2.2842079811478456724840697622497217059/000000.dcm
17,P_00127,2,RIGHT,MLO,1,calcification,PLEOMORPHIC,CLUSTERED,4,MALIGNANT,3,Calc-Test_P_00127_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.404823705712101112613641274052236131602/1.3.6.1.4.1.9590.100.1.2.90066757213729410240080160501989256297/000000.dcm,Calc-Test_P_00127_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.75530360112515908613083375823571521931/1.3.6.1.4.1.9590.100.1.2.299587177611699429507624139662621333642/000001.dcm\n,Calc-Test_P_00127_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.75530360112515908613083375823571521931/1.3.6.1.4.1.9590.100.1.2.299587177611699429507624139662621333642/000000.dcm
18,P_00132,4,LEFT,MLO,1,calcification,AMORPHOUS,SEGMENTAL,4,BENIGN,2,Calc-Test_P_00132_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.194593510212058182320671200433557462264/1.3.6.1.4.1.9590.100.1.2.97077337711594266526257744642271450347/000000.dcm,Calc-Test_P_00132_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.50246938511491296209810620281608672411/1.3.6.1.4.1.9590.100.1.2.344944500511703781234576992042730501116/000001.dcm\n,Calc-Test_P_00132_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.50246938511491296209810620281608672411/1.3.6.1.4.1.9590.100.1.2.344944500511703781234576992042730501116/000000.dcm
19,P_00140,2,LEFT,CC,1,calcification,PUNCTATE,NaN,2,BENIGN_WITHOUT_CALLBACK,5,Calc-Test_P_00140_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.207673804211103557441193847251640642407/1.3.6.1.4.1.9590.100.1.2.274130392610570391808711256560834154926/000000.dcm,Calc-Test_P_00140_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.302188895313090240911225716800874624559/1.3.6.1.4.1.9590.100.1.2.4659966412584861539173971341141804856/000001.dcm\n,Calc-Test_P_00140_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.302188895313090240911225716800874624559/1.3.6.1.4.1.9590.100.1.2.4659966412584861539173971341141804856/000000.dcm
20,P_00140,2,LEFT,CC,2,calcification,PUNCTATE,NaN,2,BENIGN_WITHOUT_CALLBACK,5,Calc-Test_P_00140_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.207673804211103557441193847251640642407/1.3.6.1.4.1.9590.100.1.2.274130392610570391808711256560834154926/000000.dcm,Calc-Test_P_00140_LEFT_CC_2/1.3.6.1.4.1.9590.100.1.2.419888238011964143222835071250111615716/1.3.6.1.4.1.9590.100.1.2.159577564313206138736036899143554653633/000001.dcm\n,Calc-Test_P_00140_LEFT_CC_2/1.3.6.1.4.1.9590.100.1.2.419888238011964143222835071250111615716/1.3.6.1.4.1.9590.100.1.2.159577564313206138736036899143554653633/000000.dcm
21,P_00140,2,LEFT,MLO,1,calcification,PUNCTATE,NaN,2,BENIGN_WITHOUT_CALLBACK,5,Calc-Test_P_00140_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.425425999111981459007730827801424873345/1.3.6.1.4.1.9590.100.1.2.160774588912073940140978200673940941357/000000.dcm,Calc-Test_P_00140_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.300686621111624918906571114460426487649/1.3.6.1.4.1.9590.100.1.2.122455910211950267836638642301512986260/000001.dcm\n,Calc-Test_P_00140_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.300686621111624918906571114460426487649/1.3.6.1.4.1.9590.100.1.2.122455910211950267836638642301512986260/000000.dcm
22,P_00140,2,LEFT,MLO,2,calcification,PUNCTATE,NaN,2,BENIGN_WITHOUT_CALLBACK,5,Calc-Test_P_00140_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.425425999111981459007730827801424873345/1.3.6.1.4.1.9590.100.1.2.160774588912073940140978200673940941357/000000.dcm,Calc-Test_P_00140_LEFT_MLO_2/1.3.6.1.4.1.9590.100.1.2.351509347912850147730952933560555549722/1.3.6.1.4.1.9590.100.1.2.189123099112918998732273238160123496951/000001.dcm\n,Calc-Test_P_00140_LEFT_MLO_2/1.3.6.1.4.1.9590.100.1.2.351509347912850147730952933560555549722/1.3.6.1.4.1.9590.100.1.2.189123099112918998732273238160123496951/000000.dcm
23,P_00140,2,RIGHT,CC,1,calcification,PUNCTATE,NaN,2,BENIGN_WITHOUT_CALLBACK,5,Calc-Test_P_00140_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.177361423111653944027713911481301007513/1.3.6.1.4.1.9590.100.1.2.166306213011523167100206271232508074491/000000.dcm,Calc-Test_P_00140_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.183529675711145261712392388233837749488/1.3.6.1.4.1.9590.100.1.2.411966477213014359701383742861949912247/000001.dcm\n,Calc-Test_P_00140_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.183529675711145261712392388233837749488/1.3.6.1.4.1.9590.100.1.2.411966477213014359701383742861949912247/000000.dcm
24,P_00140,2,RIGHT,CC,2,calcification,PUNCTATE,NaN,2,BENIGN_WITHOUT_CALLBACK,5,Calc-Test_P_00140_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.177361423111653944027713911481301007513/1.3.6.1.4.1.9590.100.1.2.166306213011523167100206271232508074491/000000.dcm,Calc-Test_P_00140_RIGHT_CC_2/1.3.6.1.4.1.9590.100.1.2.236780380112861319221904920620708235287/1.3.6.1.4.1.9590.100.1.2.265873740613852358821932576032831781816/000001.dcm\n,Calc-Test_P_00140_RIGHT_CC_2/1.3.6.1.4.1.9590.100.1.2.236780380112861319221904920620708235287/1.3.6.1.4.1.9590.100.1.2.265873740613852358821932576032831781816/000000.dcm
25,P_00140,2,RIGHT,MLO,1,calcification,PUNCTATE,NaN,2,BENIGN_WITHOUT_CALLBACK,5,Calc-Test_P_00140_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.259749192511820032606351371581395160040/1.3.6.1.4.1.9590.100.1.2.330857446012977397138099882753167890565/000000.dcm,Calc-Test_P_00140_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.197614465011522020315855205621365557275/1.3.6.1.4.1.9590.100.1.2.76850501910864026526577757561281665269/000001.dcm\n,Calc-Test_P_00140_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.197614465011522020315855205621365557275/1.3.6.1.4.1.9590.100.1.2.76850501910864026526577757561281665269/000000.dcm
26,P_00140,2,RIGHT,MLO,2,calcification,PUNCTATE,NaN,2,BENIGN_WITHOUT_CALLBACK,5,Calc-Test_P_00140_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.259749192511820032606351371581395160040/1.3.6.1.4.1.9590.100.1.2.330857446012977397138099882753167890565/000000.dcm,Calc-Test_P_00140_RIGHT_MLO_2/1.3.6.1.4.1.9590.100.1.2.130784779112520721616957080681232445774/1.3.6.1.4.1.9590.100.1.2.95827779212255247438183443413984592392/000001.dcm\n,Calc-Test_P_00140_RIGHT_MLO_2/1.3.6.1.4.1.9590.100.1.2.130784779112520721616957080681232445774/1.3.6.1.4.1.9590.100.1.2.95827779212255247438183443413984592392/000000.dcm
27,P_00141,1,LEFT,CC,1,calcification,AMORPHOUS,CLUSTERED,4,BENIGN,2,Calc-Test_P_00141_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.178857961212194190028926752161715518449/1.3.6.1.4.1.9590.100.1.2.31530197011146306721503417840497423357/000000.dcm,Calc-Test_P_00141_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.256141081410886290729430181220263631788/1.3.6.1.4.1.9590.100.1.2.405140190212844073842668438022072159427/000001.dcm\n,Calc-Test_P_00141_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.256141081410886290729430181220263631788/1.3.6.1.4.1.9590.100.1.2.405140190212844073842668438022072159427/000000.dcm
28,P_00141,1,LEFT,MLO,1,calcification,AMORPHOUS,CLUSTERED,4,BENIGN,2,Calc-Test_P_00141_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.270224245610185773912906395151111786420/1.3.6.1.4.1.9590.100.1.2.59895013913203402813556087471326658669/000000.dcm,Calc-Test_P_00141_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.132470396811132802311388148633431047614/1.3.6.1.4.1.9590.100.1.2.319647729912087119402966470430252610901/000001.dcm\n,Calc-Test_P_00141_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.132470396811132802311388148633431047614/1.3.6.1.4.1.9590.100.1.2.319647729912087119402966470430252610901/000000.dcm
29,P_00150,3,RIGHT,MLO,1,calcification,PLEOMORPHIC,CLUSTERED,4,MALIGNANT,2,Calc-Test_P_00150_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.371331409111355117622350419550343065980/1.3.6.1.4.1.9590.100.1.2.114501333713829221314528651860576350917/000000.dcm,Calc-Test_P_00150_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.376721177211032838020021000981318985410/1.3.6.1.4.1.9590.100.1.2.34010857811423811530097763121474154168/000001.dcm\n,Calc-Test_P_00150_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.376721177211032838020021000981318985410/1.3.6.1.4.1.9590.100.1.2.34010857811423811530097763121474154168/000000.dcm
30,P_00163,1,LEFT,CC,1,calcification,PLEOMORPHIC,CLUSTERED,4,BENIGN,4,Calc-Test_P_00163_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.102307995713574140823712861903467914035/1.3.6.1.4.1.9590.100.1.2.418134355612932102030136849102116704357/000000.dcm,Calc-Test_P_00163_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.179628849910914139515978505450559503198/1.3.6.1.4.1.9590.100.1.2.42126686613433025808111325632083700072/000001.dcm\n,Calc-Test_P_00163_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.179628849910914139515978505450559503198/1.3.6.1.4.1.9590.100.1.2.42126686613433025808111325632083700072/000000.dcm
31,P_00163,1,LEFT,MLO,1,calcification,PLEOMORPHIC,CLUSTERED,4,BENIGN,4,Calc-Test_P_00163_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.219084259611341474834321906141067760281/1.3.6.1.4.1.9590.100.1.2.355621977111644810605764135772022462045/000000.dcm,Calc-Test_P_00163_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.298127237611801162114488598243132285951/1.3.6.1.4.1.9590.100.1.2.10137222212212542240654112083474386222/000001.dcm\n,Calc-Test_P_00163_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.298127237611801162114488598243132285951/1.3.6.1.4.1.9590.100.1.2.10137222212212542240654112083474386222/000000.dcm
32,P_00164,4,RIGHT,CC,1,calcification,PLEOMORPHIC,CLUSTERED,4,MALIGNANT,3,Calc-Test_P_00164_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.198671590012596483413328889620965677973/1.3.6.1.4.1.9590.100.1.2.101282442711963955211635160453427358442/000000.dcm,Calc-Test_P_00164_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.58097554011501135534524929821906717931/1.3.6.1.4.1.9590.100.1.2.285626242111110244620205656484034039759/000001.dcm\n,Calc-Test_P_00164_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.58097554011501135534524929821906717931/1.3.6.1.4.1.9590.100.1.2.285626242111110244620205656484034039759/000000.dcm

In [2]:
df2 = pd.read_csv('calc_case_description_test_set.csv')
df2.head(8)

,patient_id,breast_density,left or right breast,image view,abnormality id,abnormality type,mass shape,mass margins,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path
0,P_00016,4,LEFT,CC,1,mass,IRREGULAR,SPICULATED,5,MALIGNANT,5,Mass-Test_P_00016_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.416403281812750683720028031170500130104/1.3.6.1.4.1.9590.100.1.2.245063149211255120613007755642780114172/000000.dcm,Mass-Test_P_00016_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.259596319110047779433501728143778409887/1.3.6.1.4.1.9590.100.1.2.30820586311062570442302321942433426184/000000.dcm,Mass-Test_P_00016_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.259596319110047779433501728143778409887/1.3.6.1.4.1.9590.100.1.2.30820586311062570442302321942433426184/000001.dcm\n
1,P_00016,4,LEFT,MLO,1,mass,IRREGULAR,SPICULATED,5,MALIGNANT,5,Mass-Test_P_00016_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.125010935311829990124529079264106154392/1.3.6.1.4.1.9590.100.1.2.85952214611170506017891429690540035518/000000.dcm,Mass-Test_P_00016_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.207144238612220754118040203520552715563/1.3.6.1.4.1.9590.100.1.2.381440141511137044327302306604206077287/000000.dcm,Mass-Test_P_00016_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.207144238612220754118040203520552715563/1.3.6.1.4.1.9590.100.1.2.381440141511137044327302306604206077287/000001.dcm\n
2,P_00017,2,LEFT,CC,1,mass,ROUND,CIRCUMSCRIBED,4,MALIGNANT,4,Mass-Test_P_00017_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.289610447411344525237308079592285912683/1.3.6.1.4.1.9590.100.1.2.22131189612893294827907969600765582967/000000.dcm,Mass-Test_P_00017_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.265130777712709757209861180301164730118/1.3.6.1.4.1.9590.100.1.2.212143028513012144941507232513982203672/000000.dcm,Mass-Test_P_00017_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.265130777712709757209861180301164730118/1.3.6.1.4.1.9590.100.1.2.212143028513012144941507232513982203672/000001.dcm\n
3,P_00017,2,LEFT,MLO,1,mass,ROUND,ILL_DEFINED,4,MALIGNANT,4,Mass-Test_P_00017_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.22378064110931464632702821421529389998/1.3.6.1.4.1.9590.100.1.2.239949064412092068706566726490415129934/000000.dcm,Mass-Test_P_00017_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.66862495211464129620756742774012127297/1.3.6.1.4.1.9590.100.1.2.15403043813402510742192372832381918984/000000.dcm,Mass-Test_P_00017_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.66862495211464129620756742774012127297/1.3.6.1.4.1.9590.100.1.2.15403043813402510742192372832381918984/000001.dcm\n
4,P_00032,3,RIGHT,CC,1,mass,ROUND,OBSCURED,0,BENIGN,2,Mass-Test_P_00032_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.304236983211992984124654432490357131069/1.3.6.1.4.1.9590.100.1.2.215081818713600536113960661873725083371/000000.dcm,Mass-Test_P_00032_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.362221700813915332616463215463274950690/1.3.6.1.4.1.9590.100.1.2.199593071810497070809647901570077988031/000000.dcm,Mass-Test_P_00032_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.362221700813915332616463215463274950690/1.3.6.1.4.1.9590.100.1.2.199593071810497070809647901570077988031/000001.dcm\n
5,P_00032,3,RIGHT,MLO,1,mass,ROUND,OBSCURED,0,BENIGN,2,Mass-Test_P_00032_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.383460844111861145315621774372145221963/1.3.6.1.4.1.9590.100.1.2.318799084911119262430780458250312419361/000000.dcm,Mass-Test_P_00032_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.247343732911042250406750122270776949655/1.3.6.1.4.1.9590.100.1.2.44610919611642954332266410812181604922/000000.dcm,Mass-Test_P_00032_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.247343732911042250406750122270776949655/1.3.6.1.4.1.9590.100.1.2.44610919611642954332266410812181604922/000001.dcm\n
6,P_00037,3,RIGHT,CC,1,mass,ROUND,SPICULATED,5,MALIGNANT,5,Mass-Test_P_00037_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.103263415712637900541513993551878074559/1.3.6.1.4.1.9590.100.1.2.345140832810160378520078721331878282316/000000.dcm,Mass-Test_P_00037_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.51371400012281630410382188863446338107/1.3.6.1.4.1.9590.100.1.2.335564193512609498716387099372607181452/000000.dcm,Mass-Test_P_00037_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.51371400012281630410382188863446338107/1.3.6.1.4.1.9590.100.1.2.335564193512609498716387099372607181452/000001.dcm\n
7,P_00037,3,RIGHT,MLO,1,mass,IRREGULAR,SPICULATED,5,MALIGNANT,5,Mass-Test_P_00037_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.49507331912048398437734209542790648441/1.3.6.1.4.1.9590.100.1.2.59887648512379053809277845872128232362/000000.dcm,Mass-Test_P_00037_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.212527445411669219116084453571752862492/1.3.6.1.4.1.9590.100.1.2.371211525812372459428004652923830584055/000000.dcm,Mass-Test_P_00037_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.212527445411669219116084453571752862492/1.3.6.1.4.1.9590.100.1.2.371211525812372459428004652923830584055/000001.dcm\n

In [3]:
print(df2.info())
print(df2['image file path'][75])
print(df2['cropped image file path'][3])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378 entries, 0 to 377
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   patient_id               378 non-null    object
 1   breast_density           378 non-null    int64
 2   left or right breast     378 non-null    object
 3   image view               378 non-null    object
 4   abnormality id           378 non-null    int64
 5   abnormality type         378 non-null    object
 6   mass shape               378 non-null    object
 7   mass margins             361 non-null    object
 8   assessment               378 non-null    int64
 9   pathology                378 non-null    object
 10  subtlety                 378 non-null    int64
 11  image file path          378 non-null    object
 12  cropped image file path  378 non-null    object
 13  ROI mask file path       378 non-null    object
dtypes: int64(4), object(10)
memory usage: 41.5+ KB
None
Mass-Test_P_00347_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.102984702812742722305823922360699156228/1.3.6.1.4.1.9590.100.1.2.328888964910420470437557917552593278246/000000.dcm
Mass-Test_P_00017_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.66862495211464129620756742774012127297/1.3.6.1.4.1.9590.100.1.2.15403043813402510742192372832381918984/000000.dcm

In [4]:
df3 = pd.read_csv('meta.csv')
df3.head(20)

,SeriesInstanceUID,StudyInstanceUID,Modality,SeriesDescription,BodyPartExamined,SeriesNumber,Collection,Visibility,ImageCount
0,1.3.6.1.4.1.9590.100.1.2.117041576511324414842508325652101471266,1.3.6.1.4.1.9590.100.1.2.229361142710768138411679379233064924540,MG,ROI mask images,BREAST,1,CBIS-DDSM,1,2
1,1.3.6.1.4.1.9590.100.1.2.43873839610761788013224723323225482381,1.3.6.1.4.1.9590.100.1.2.195593486612988388325770883972107282733,MG,ROI mask images,BREAST,1,CBIS-DDSM,1,2
2,1.3.6.1.4.1.9590.100.1.2.76741674113167646338262765132488965294,1.3.6.1.4.1.9590.100.1.2.257901172612530623323924356380431605062,MG,ROI mask images,BREAST,1,CBIS-DDSM,1,2
3,1.3.6.1.4.1.9590.100.1.2.296931352612305599800425693833437698626,1.3.6.1.4.1.9590.100.1.2.109468616710242115222536802734027827120,MG,ROI mask images,BREAST,1,CBIS-DDSM,1,2
4,1.3.6.1.4.1.9590.100.1.2.43665767012035310007732414810147712942,1.3.6.1.4.1.9590.100.1.2.380627129513562450304304820723973964760,MG,ROI mask images,BREAST,1,CBIS-DDSM,1,2
5,1.3.6.1.4.1.9590.100.1.2.245633900110007082034118990512969470333,1.3.6.1.4.1.9590.100.1.2.143790815011189157220543617630697462001,MG,ROI mask images,BREAST,1,CBIS-DDSM,1,2
6,1.3.6.1.4.1.9590.100.1.2.45131627713144582424202640662752027993,1.3.6.1.4.1.9590.100.1.2.310228111811303452111342857131681135070,MG,ROI mask images,BREAST,1,CBIS-DDSM,1,2
7,1.3.6.1.4.1.9590.100.1.2.321062807811123845106490625560193258924,1.3.6.1.4.1.9590.100.1.2.195655760513031195523320296122940320213,MG,cropped images,BREAST,1,CBIS-DDSM,1,1
8,1.3.6.1.4.1.9590.100.1.2.203989029910964209440425982812598330086,1.3.6.1.4.1.9590.100.1.2.222512969612930058132185640213545114412,MG,ROI mask images,BREAST,1,CBIS-DDSM,1,1
9,1.3.6.1.4.1.9590.100.1.2.59331645212722964919598145441897056623,1.3.6.1.4.1.9590.100.1.2.407538725111828839342756496710990319312,MG,ROI mask images,BREAST,1,CBIS-DDSM,1,2
10,1.3.6.1.4.1.9590.100.1.2.141408387111896887000146541221335162897,1.3.6.1.4.1.9590.100.1.2.158040480311082280514489245583038014273,MG,ROI mask images,BREAST,1,CBIS-DDSM,1,2
11,1.3.6.1.4.1.9590.100.1.2.68828333511045311425255190220373462995,1.3.6.1.4.1.9590.100.1.2.68211530212301111920151819731835709761,MG,ROI mask images,BREAST,1,CBIS-DDSM,1,2
12,1.3.6.1.4.1.9590.100.1.2.272420956211500194613015855910561320194,1.3.6.1.4.1.9590.100.1.2.85444085411996591832008959121652619717,MG,ROI mask images,BREAST,1,CBIS-DDSM,1,2
13,1.3.6.1.4.1.9590.100.1.2.33355931610429994428806391080346623398,1.3.6.1.4.1.9590.100.1.2.365905386611571212328956412520064192793,MG,ROI mask images,BREAST,1,CBIS-DDSM,1,2
14,1.3.6.1.4.1.9590.100.1.2.159789089511044436630882300743522788770,1.3.6.1.4.1.9590.100.1.2.388555962412314837506487579223622875564,MG,ROI mask images,BREAST,1,CBIS-DDSM,1,1
15,1.3.6.1.4.1.9590.100.1.2.56869035110310903317304482733636502883,1.3.6.1.4.1.9590.100.1.2.193280672812371093303940934982464215402,MG,cropped images,BREAST,1,CBIS-DDSM,1,1
16,1.3.6.1.4.1.9590.100.1.2.296736403313792599626368780122205399650,1.3.6.1.4.1.9590.100.1.2.108268213011361124203859148071588939106,MG,ROI mask images,BREAST,1,CBIS-DDSM,1,2
17,1.3.6.1.4.1.9590.100.1.2.64813381212358693815004901263092702152,1.3.6.1.4.1.9590.100.1.2.343151401613385821008920899863910962163,MG,ROI mask images,BREAST,1,CBIS-DDSM,1,2
18,1.3.6.1.4.1.9590.100.1.2.288520517011500966318936802952535540775,1.3.6.1.4.1.9590.100.1.2.369517521412718360228989065571179179554,MG,ROI mask images,BREAST,1,CBIS-DDSM,1,2
19,1.3.6.1.4.1.9590.100.1.2.147482114012307911938186633001212085130,1.3.6.1.4.1.9590.100.1.2.4586106112860215003690049533853711471,MG,ROI mask images,BREAST,1,CBIS-DDSM,1,2

In [5]:
print(df3.info())
print(df3['SeriesInstanceUID'][3])
print(df3['StudyInstanceUID'][3])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6775 entries, 0 to 6774
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SeriesInstanceUID  6775 non-null   object
 1   StudyInstanceUID   6775 non-null   object
 2   Modality           6775 non-null   object
 3   SeriesDescription  6775 non-null   object
 4   BodyPartExamined   6775 non-null   object
 5   SeriesNumber       6775 non-null   int64
 6   Collection         6775 non-null   object
 7   Visibility         6775 non-null   int64
 8   ImageCount         6775 non-null   int64
dtypes: int64(3), object(6)
memory usage: 476.5+ KB
None
1.3.6.1.4.1.9590.100.1.2.296931352612305599800425693833437698626
1.3.6.1.4.1.9590.100.1.2.109468616710242115222536802734027827120

In [6]:
df4 = pd.read_csv('dicom_info.csv')
df4.head(20)

,file_path,image_path,AccessionNumber,BitsAllocated,BitsStored,BodyPartExamined,Columns,ContentDate,ContentTime,ConversionType,HighBit,InstanceNumber,LargestImagePixelValue,Laterality,Modality,PatientBirthDate,PatientID,PatientName,PatientOrientation,PatientSex,PhotometricInterpretation,PixelRepresentation,ReferringPhysicianName,Rows,SOPClassUID,SOPInstanceUID,SamplesPerPixel,SecondaryCaptureDeviceManufacturer,SecondaryCaptureDeviceManufacturerModelName,SeriesDescription,SeriesInstanceUID,SeriesNumber,SmallestImagePixelValue,SpecificCharacterSet,StudyDate,StudyID,StudyInstanceUID,StudyTime
0,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.129308726812851964007517874181459556304/1-172.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.129308726812851964007517874181459556304/1-172.jpg,NaN,16,16,BREAST,351,20160426,131732.685,WSD,15,1,65535,R,MG,NaN,Mass-Training_P_01265_RIGHT_MLO_1,Mass-Training_P_01265_RIGHT_MLO_1,MLO,NaN,MONOCHROME2,0,NaN,289,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.426380754911844882201419900442081103076,1,MathWorks,MATLAB,cropped images,1.3.6.1.4.1.9590.100.1.2.129308726812851964007517874181459556304,1,23078,ISO_IR 100,20160720.0,DDSM,1.3.6.1.4.1.9590.100.1.2.271867287611061855725036643043149877819,214951.0
1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.248386742010678582309005372213277814849/1-249.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.248386742010678582309005372213277814849/1-249.jpg,NaN,16,16,BREAST,3526,20160426,143829.101,WSD,15,1,65535,R,MG,NaN,Mass-Training_P_01754_RIGHT_CC,Mass-Training_P_01754_RIGHT_CC,CC,NaN,MONOCHROME2,0,NaN,6256,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.235715018911442345533339224491594398571,1,MathWorks,MATLAB,full mammogram images,1.3.6.1.4.1.9590.100.1.2.248386742010678582309005372213277814849,1,0,ISO_IR 100,20160720.0,DDSM,1.3.6.1.4.1.9590.100.1.2.161516517311681906612443997862211969669,193426.0
2,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.267213171011171858918434139331210917771/1-032.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.267213171011171858918434139331210917771/1-032.jpg,NaN,16,16,BREAST,1546,20160503,111956.298,WSD,15,1,65535,R,MG,NaN,Calc-Training_P_00232_RIGHT_CC,Calc-Training_P_00232_RIGHT_CC,CC,NaN,MONOCHROME2,0,NaN,4126,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.212917405611495375422194124032450014293,1,MathWorks,MATLAB,full mammogram images,1.3.6.1.4.1.9590.100.1.2.267213171011171858918434139331210917771,1,0,ISO_IR 100,20160807.0,DDSM,1.3.6.1.4.1.9590.100.1.2.291043622711253836701017460903623585574,161814.0
3,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.381187369611524586537789902641525311317/1-052.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.381187369611524586537789902641525311317/1-052.jpg,NaN,16,16,BREAST,97,20160503,115347.770,WSD,15,1,65535,L,MG,NaN,Calc-Test_P_00562_LEFT_CC_2,Calc-Test_P_00562_LEFT_CC_2,CC,NaN,MONOCHROME2,0,NaN,97,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.405776661412249467913600188550817314766,1,MathWorks,MATLAB,cropped images,1.3.6.1.4.1.9590.100.1.2.381187369611524586537789902641525311317,1,32298,ISO_IR 100,20170829.0,DDSM,1.3.6.1.4.1.9590.100.1.2.335006093711888937440665960211609580159,180109.0
4,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.381187369611524586537789902641525311317/2-204.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.381187369611524586537789902641525311317/2-204.jpg,NaN,8,8,Left Breast,3104,20160503,115347.770,WSD,7,1,255,NaN,MG,NaN,P_00562_LEFT_CC_2.dcm,P_00562^P_00562,CC,NaN,MONOCHROME2,0,NaN,4560,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.418434643810489919922754459191670588257,1,MathWorks,MATLAB,NaN,1.3.6.1.4.1.9590.100.1.2.381187369611524586537789902641525311317,1,0,ISO_IR 100,NaN,DDSM,1.3.6.1.4.1.9590.100.1.2.335006093711888937440665960211609580159,NaN
5,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.153339052913121382622526066491844156138/2-270.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.153339052913121382622526066491844156138/2-270.jpg,NaN,8,8,BREAST,1981,20160503,111620.055,WSD,7,1,255,R,MG,NaN,Calc-Training_P_00181_RIGHT_CC_1,Calc-Training_P_00181_RIGHT_CC_1,CC,NaN,MONOCHROME2,0,NaN,3931,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.265034136111320280631350286570362826143,1,MathWorks,MATLAB,ROI mask images,1.3.6.1.4.1.9590.100.1.2.153339052913121382622526066491844156138,1,0,ISO_IR 100,20170906.0,DDSM,1.3.6.1.4.1.9590.100.1.2.157384031212566921514825155931159088272,82702.0
6,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.153339052913121382622526066491844156138/1-034.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.153339052913121382622526066491844156138/1-034.jpg,NaN,16,16,BREAST,393,20160503,111620.055,WSD,15,1,65535,R,MG,NaN,Calc-Training_P_00181_RIGHT_CC_1,Calc-Training_P_00181_RIGHT_CC_1,CC,NaN,MONOCHROME2,0,NaN,409,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.398771175312365272736850154561242740396,1,MathWorks,MATLAB,cropped images,1.3.6.1.4.1.9590.100.1.2.153339052913121382622526066491844156138,1,44323,ISO_IR 100,20170830.0,DDSM,1.3.6.1.4.1.9590.100.1.2.157384031212566921514825155931159088272,215032.0
7,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.178994714611485132105265512043047466091/1-149.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.178994714611485132105265512043047466091/1-149.jpg,NaN,16,16,BREAST,611,20160503,122938.838,WSD,15,1,65535,L,MG,NaN,Calc-Training_P_01015_LEFT_CC_1,Calc-Training_P_01015_LEFT_CC_1,CC,NaN,MONOCHROME2,0,NaN,436,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.131386567811700111319452363910019920460,1,MathWorks,MATLAB,cropped images,1.3.6.1.4.1.9590.100.1.2.178994714611485132105265512043047466091,1,24057,ISO_IR 100,20170830.0,DDSM,1.3.6.1.4.1.9590.100.1.2.250103550412831547020129914092630564214,215300.0
8,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.178994714611485132105265512043047466091/2-127.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.178994714611485132105265512043047466091/2-127.jpg,NaN,8,8,BREAST,3571,20160503,122938.838,WSD,7,1,255,L,MG,NaN,Calc-Training_P_01015_LEFT_CC_1,Calc-Training_P_01015_LEFT_CC_1,CC,NaN,MONOCHROME2,0,NaN,5056,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.294915843610022454741553588541121097197,1,MathWorks,MATLAB,ROI mask images,1.3.6.1.4.1.9590.100.1.2.178994714611485132105265512043047466091,1,0,ISO_IR 100,20170906.0,DDSM,1.3.6.1.4.1.9590.100.1.2.250103550412831547020129914092630564214,84849.0
9,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.411833492612373627114350673042828631265/2-281.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.411833492612373627114350673042828631265/2-281.jpg,NaN,8,8,BREAST,2371,20160503,131321.302,WSD,7,1,255,L,MG,NaN,Calc-Training_P_01497_LEFT_CC_1,Calc-Training_P_01497_LEFT_CC_1,CC,NaN,MONOCHROME2,0,NaN,5491,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.31877902510224359240285438880068008991,1,MathWorks,MATLAB,ROI mask images,1.3.6.1.4.1.9590.100.1.2.411833492612373627114350673042828631265,1,0,ISO_IR 100,20170906.0,DDSM,1.3.6.1.4.1.9590.100.1.2.407544576612957992910008088802256409844,90204.0
10,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.411833492612373627114350673042828631265/1-003.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.411833492612373627114350673042828631265/1-003.jpg,NaN,16,16,BREAST,809,20160503,131321.302,WSD,15,1,65535,L,MG,NaN,Calc-Training_P_01497_LEFT_CC_1,Calc-Training_P_01497_LEFT_CC_1,CC,NaN,MONOCHROME2,0,NaN,1217,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.52904922613360974328117797322115657536,1,MathWorks,MATLAB,cropped images,1.3.6.1.4.1.9590.100.1.2.411833492612373627114350673042828631265,1,0,ISO_IR 100,20170830.0,DDSM,1.3.6.1.4.1.9590.100.1.2.407544576612957992910008088802256409844,215430.0
11,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.210396893911234385024533119100226540488/1-128.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.210396893911234385024533119100226540488/1-128.jpg,NaN,16,16,BREAST,2491,20160426,130913.563,WSD,15,1,65534,R,MG,NaN,Mass-Training_P_01206_RIGHT_MLO,Mass-Training_P_01206_RIGHT_MLO,MLO,NaN,MONOCHROME2,0,NaN,5491,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.293676638212708973026730866050179561554,1,MathWorks,MATLAB,full mammogram images,1.3.6.1.4.1.9590.100.1.2.210396893911234385024533119100226540488,1,0,ISO_IR 100,20160720.0,DDSM,1.3.6.1.4.1.9590.100.1.2.84796691012850669804412676330103000334,190507.0
12,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.74956658311383957201426978750903861062/1-248.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.74956658311383957201426978750903861062/1-248.jpg,NaN,16,16,BREAST,4040,20160503,114631.174,WSD,15,1,65535,R,MG,NaN,Calc-Training_P_00506_RIGHT_MLO,Calc-Training_P_00506_RIGHT_MLO,MLO,NaN,MONOCHROME2,0,NaN,5720,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.92913625712286714917520442071321959914,1,MathWorks,MATLAB,full mammogram images,1.3.6.1.4.1.9590.100.1.2.74956658311383957201426978750903861062,1,0,ISO_IR 100,20160807.0,DDSM,1.3.6.1.4.1.9590.100.1.2.199136909412566562327823164590163451498,162929.0
13,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.236373548712994183418851990043419770402/1-085.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.236373548712994183418851990043419770402/1-085.jpg,NaN,16,16,BREAST,365,20160426,110203.716,WSD,15,1,65535,R,MG,NaN,Mass-Training_P_00242_RIGHT_CC_1,Mass-Training_P_00242_RIGHT_CC_1,CC,NaN,MONOCHROME2,0,NaN,343,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.319798184110947728636541707683476242400,1,MathWorks,MATLAB,cropped images,1.3.6.1.4.1.9590.100.1.2.236373548712994183418851990043419770402,1,26731,ISO_IR 100,20160720.0,DDSM,1.3.6.1.4.1.9590.100.1.2.167269008112450091603531682673795482920,214721.0
14,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.236373548712994183418851990043419770402/2-086.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.236373548712994183418851990043419770402/2-086.jpg,NaN,8,8,BREAST,2760,20160426,110203.716,WSD,7,1,255,R,MG,NaN,Mass-Training_P_00242_RIGHT_CC_1,Mass-Training_P_00242_RIGHT_CC_1,CC,NaN,MONOCHROME2,0,NaN,4600,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.146008698813215384122346779490462063447,1,MathWorks,MATLAB,ROI mask images,1.3.6.1.4.1.9590.100.1.2.236373548712994183418851990043419770402,1,0,ISO_IR 100,20160721.0,DDSM,1.3.6.1.4.1.9590.100.1.2.167269008112450091603531682673795482920,83341.0
15,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.98765885412946410823689524902893984551/1-007.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.98765885412946410823689524902893984551/1-007.jpg,NaN,16,16,BREAST,3080,20160503,133703.461,WSD,15,1,65535,R,MG,NaN,Calc-Training_P_01823_RIGHT_CC,Calc-Training_P_01823_RIGHT_CC,CC,NaN,MONOCHROME2,0,NaN,4560,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.29974419610429041701332891043406930225,1,MathWorks,MATLAB,full mammogram images,1.3.6.1.4.1.9590.100.1.2.98765885412946410823689524902893984551,1,0,ISO_IR 100,20160807.0,DDSM,1.3.6.1.4.1.9590.100.1.2.240827364811492781021164100041265238830,171811.0
16,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.362722981912364196037055929741492450134/1-074.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.362722981912364196037055929741492450134/1-074.jpg,NaN,16,16,BREAST,2920,20160426,104711.161,WSD,15,1,61031,R,MG,NaN,Mass-Training_P_00122_RIGHT_MLO,Mass-Training_P_00122_RIGHT_MLO,MLO,NaN,MONOCHROME2,0,NaN,4592,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.371248673512749638101100018444282690032,1,MathWorks,MATLAB,full mammogram images,1.3.6.1.4.1.9590.100.1.2.362722981912364196037055929741492450134,1,0,ISO_IR 100,20160720.0,DDSM,1.3.6.1.4.1.9590.100.1.2.23102643111095874815641619593788162692,181717.0
17,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.106891403212241567917640106401990119369/1-007.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.106891403212241567917640106401990119369/1-007.jpg,NaN,16,16,BREAST,2920,20160426,130507.215,WSD,15,1,65535,R,MG,NaN,Mass-Training_P_01175_RIGHT_MLO,Mass-Training_P_01175_RIGHT_MLO,MLO,NaN,MONOCHROME2,0,NaN,4784,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.274350832311816359332661748804077481865,1,MathWorks,MATLAB,full mammogram images,1.3.6.1.4.1.9590.100.1.2.106891403212241567917640106401990119369,1,0,ISO_IR 100,20160720.0,DDSM,1.3.6.1.4.1.9590.100.1.2.177354308713631618239839681791678458762,190245.0
18,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.121186059612438420227614821281510350601/1-086.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.121186059612438420227614821281510350601/1-086.jpg,NaN,16,16,BREAST,3704,20160426,112023.115,WSD,15,1,56496,R,MG,NaN,Mass-Training_P_00411_RIGHT_CC,Mass-Training_P_00411_RIGHT_CC,CC,NaN,MONOCHROME2,0,NaN,5704,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.10467752712432278214442771273486593408,1,MathWorks,MATLAB,full mammogram images,1.3.6.1.4.1.9590.100.1.2.121186059612438420227614821281510350601,1,0,ISO_IR 100,20160720.0,DDSM,1.3.6.1.4.1.9590.100.1.2.215382355611190781042924678780032735980,182610.0
19,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.357008050412534761329866492500201501919/2-242.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.357008050412534761329866492500201501919/2-242.jpg,NaN,16,16,BREAST,330,20160426,115110.499,WSD,15,1,65535,R,MG,NaN,Mass-Training_P_00634_RIGHT_MLO_1,Mass-Training_P_00634_RIGHT_MLO_1,MLO,NaN,MONOCHROME2,0,NaN,492,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.235627801710946370605209317283350814021,1,MathWorks,MATLAB,cropped images,1.3.6.1.4.1.9590.100.1.2.357008050412534761329866492500201501919,1,34584,ISO_IR 100,20160720.0,DDSM,1.3.6.1.4.1.9590.100.1.2.48574144512341818729802725191876421125,214818.0

In [7]:
print(df4['file_path'][3])
print(df4['image_path'][3])

CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.381187369611524586537789902641525311317/1-052.dcm
CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.381187369611524586537789902641525311317/1-052.jpg

Podemos ver que hay un csv que contiene fotos con lesiones con calcificaciones, donde te dice el tipo de anormalidad, el tipo de calcificación, su distribución, otros datos, su patología (benigno o maligno) y las rutas a cada imagen: la que es mmografía completa, la que es recortada en la región de interés, y la máscara binaria del tumor píxel a píxel. También nos dicen el ID del paciente para cada foto, si es la teta izquierda o derecha y el punto de vista de la imagen (CC es desde arriba y MLO de perfil). Por tanto, para empezar conviene separar las imágenes que son mamografía completa de las que son recortes y de las máscaras. También convendría cambiarles el nombre a las imágenes (quizá poner info sobre el tumor en el propio nombre).

OBSERVACIONES: El csv de calc y calc no parece ser por foto, sino por tipo de lesión, por eso hay tan pocos. En la image file path contiene una cosa rara, mezcla de varios IDs, no la ruta a una foto en concreto del dataset. De esa ruta hay que coger el studentUID y, con él, vamos al csv de dicom. En él cada fila sí corresponde a una única foto. Con ese studentUID identificamos todas las fotos con esa lesión, pues todas tienen asociado el mismo student ID. Hacemos un dataframe con todas las fotos y sus cosas. El que extrajo esto es subnormal profundo: es muy difícil identificar la lesión de cada imágenes con estos csv. Hay que hacer una combinación de varios para lograr algo.
ADEMÁS, la única informaciónn histológica fuerte es BENING / MALIGN. Es decir, no podemos clasificar el tipo de tumor. Solo si es benigno o maligno. Esto es una mierda, la verdad. EL INBreast creo que tampoco te permite hacer eso.

In [8]:
# ============================
# 2. CARGAR CSVs
# ============================

mass = pd.read_csv('mass_case_description_train_set.csv')
meta = pd.read_csv('meta.csv')
dicom = pd.read_csv('dicom_info.csv')

# ============================
# 3. EXTRAER StudyUID y SeriesUID DEL image_file_path
# ============================

mass["StudyInstanceUID"] = mass["image file path"].str.split("/").str[1]
mass["SeriesInstanceUID"] = mass["image file path"].str.split("/").str[2]

# ============================
# 4. MERGE MASS ↔ META (para saber cuántas imágenes tiene la serie)
# ============================

mass_meta = mass.merge(meta, on=["StudyInstanceUID", "SeriesInstanceUID"], how="left")

# ============================
# 5. MERGE MASS_META ↔ DICOM_INFO (para obtener rutas JPEG reales)
# ============================

mass_full = mass_meta.merge(dicom, on=["StudyInstanceUID", "SeriesInstanceUID"], how="left")
mass_full.head(10)

,patient_id,breast_density,left or right breast,image view,abnormality id,abnormality type,mass shape,mass margins,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path,StudyInstanceUID,SeriesInstanceUID,Modality_x,SeriesDescription_x,BodyPartExamined_x,SeriesNumber_x,Collection,Visibility,ImageCount,file_path,image_path,AccessionNumber,BitsAllocated,BitsStored,BodyPartExamined_y,Columns,ContentDate,ContentTime,ConversionType,HighBit,InstanceNumber,LargestImagePixelValue,Laterality,Modality_y,PatientBirthDate,PatientID,PatientName,PatientOrientation,PatientSex,PhotometricInterpretation,PixelRepresentation,ReferringPhysicianName,Rows,SOPClassUID,SOPInstanceUID,SamplesPerPixel,SecondaryCaptureDeviceManufacturer,SecondaryCaptureDeviceManufacturerModelName,SeriesDescription_y,SeriesNumber_y,SmallestImagePixelValue,SpecificCharacterSet,StudyDate,StudyID,StudyTime
0,P_00001,3,LEFT,CC,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.422112722213189649807611434612228974994/1.3.6.1.4.1.9590.100.1.2.342386194811267636608694132590482924515/000000.dcm,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.108268213011361124203859148071588939106/1.3.6.1.4.1.9590.100.1.2.296736403313792599626368780122205399650/000000.dcm,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.108268213011361124203859148071588939106/1.3.6.1.4.1.9590.100.1.2.296736403313792599626368780122205399650/000001.dcm\n,1.3.6.1.4.1.9590.100.1.2.422112722213189649807611434612228974994,1.3.6.1.4.1.9590.100.1.2.342386194811267636608694132590482924515,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.342386194811267636608694132590482924515/1-211.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.342386194811267636608694132590482924515/1-211.jpg,NaN,16,16,BREAST,3024,20160414,121658.138,WSD,15,1,65535,L,MG,NaN,Mass-Training_P_00001_LEFT_CC,Mass-Training_P_00001_LEFT_CC,CC,NaN,MONOCHROME2,0,NaN,4808,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.156556873010981646517128874312129349516,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160720.0,DDSM,181327.0
1,P_00001,3,LEFT,MLO,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.319478999311971442426185353560182990988/1.3.6.1.4.1.9590.100.1.2.359308329312397897125630708681441180834/000000.dcm,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.188473874511440575807446266233629582526/1.3.6.1.4.1.9590.100.1.2.227955274711225756835838775062793186053/000000.dcm,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.188473874511440575807446266233629582526/1.3.6.1.4.1.9590.100.1.2.227955274711225756835838775062793186053/000001.dcm\n,1.3.6.1.4.1.9590.100.1.2.319478999311971442426185353560182990988,1.3.6.1.4.1.9590.100.1.2.359308329312397897125630708681441180834,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.359308329312397897125630708681441180834/1-207.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.359308329312397897125630708681441180834/1-207.jpg,NaN,16,16,BREAST,2656,20160414,121707.636,WSD,15,1,65535,L,MG,NaN,Mass-Training_P_00001_LEFT_MLO,Mass-Training_P_00001_LEFT_MLO,MLO,NaN,MONOCHROME2,0,NaN,4800,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.16927317613478383512517710492717097139,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160720.0,DDSM,181329.0
2,P_00004,3,LEFT,CC,1,mass,ARCHITECTURAL_DISTORTION,ILL_DEFINED,4,BENIGN,3,Mass-Training_P_00004_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.347107867812656628709864319310977895697/1.3.6.1.4.1.9590.100.1.2.89180046211022531834352631483669346540/000000.dcm,Mass-Training_P_00004_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.414182170112396175925115449620455230167/1.3.6.1.4.1.9590.100.1.2.429120414011832984817094399141838850375/000000.dcm,Mass-Training_P_00004_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.414182170112396175925115449620455230167/1.3.6.1.4.1.9590.100.1.2.429120414011832984817094399141838850375/000001.dcm\n,1.3.6.1.4.1.9590.100.1.2.347107867812656628709864319310977895697,1.3.6.1.4.1.9590.100.1.2.89180046211022531834352631483669346540,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.89180046211022531834352631483669346540/1-250.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.89180046211022531834352631483669346540/1-250.jpg,NaN,16,16,BREAST,2986,20160414,121712.187,WSD,15,1,65535,L,MG,NaN,Mass-Training_P_00004_LEFT_CC,Mass-Training_P_00004_LEFT_CC,CC,NaN,MONOCHROME2,0,NaN,5491,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.358480630813132072812841219952338956181,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160720.0,DDSM,181330.0
3,P_00004,3,LEFT,MLO,1,mass,ARCHITECTURAL_DISTORTION,ILL_DEFINED,4,BENIGN,3,Mass-Training_P_00004_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.272600286511817402806912403581910920939/1.3.6.1.4.1.9590.100.1.2.295360926313492745441868049270168300162/000000.dcm,Mass-Training_P_00004_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.342549219112801262604988012930063078769/1.3.6.1.4.1.9590.100.1.2.115134232113001553100559896703407510515/000000.dcm,Mass-Training_P_00004_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.342549219112801262604988012930063078769/1.3.6.1.4.1.9590.100.1.2.115134232113001553100559896703407510515/000001.dcm\n,1.3.6.1.4.1.9590.100.1.2.272600286511817402806912403581910920939,1.3.6.1.4.1.9590.100.1.2.295360926313492745441868049270168300162,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.295360926313492745441868049270168300162/1-067.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.295360926313492745441868049270168300162/1-067.jpg,NaN,16,16,BREAST,3046,20160414,121718.285,WSD,15,1,65535,L,MG,NaN,Mass-Training_P_00004_LEFT_MLO,Mass-Training_P_00004_LEFT_MLO,MLO,NaN,MONOCHROME2,0,NaN,5491,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.90094618910192524003642674112305368468,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160720.0,DDSM,181332.0
4,P_00004,3,RIGHT,MLO,1,mass,OVAL,CIRCUMSCRIBED,4,BENIGN,5,Mass-Training_P_00004_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.174047308712169195014610267031196524486/1.3.6.1.4.1.9590.100.1.2.410524754913057908920631336070876889890/000000.dcm,Mass-Training_P_00004_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.341142631111685501338932932302380583774/1.3.6.1.4.1.9590.100.1.2.12857366312625701203276284233604184846/000000.dcm,Mass-Training_P_00004_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.341142631111685501338932932302380583774/1.3.6.1.4.1.9590.100.1.2.12857366312625701203276284233604184846/000001.dcm\n,1.3.6.1.4.1.9590.100.1.2.174047308712169195014610267031196524486,1.3.6.1.4.1.9590.100.1.2.410524754913057908920631336070876889890,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.410524754913057908920631336070876889890/1-056.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.410524754913057908920631336070876889890/1-056.jpg,NaN,16,16,BREAST,2911,20160414,121728.490,WSD,15,1,65535,R,MG,NaN,Mass-Training_P_00004_RIGHT_MLO,Mass-Training_P_00004_RIGHT_MLO,MLO,NaN,MONOCHROME2,0,NaN,5491,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.342291849811940826323885305650563096625,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160720.0,DDSM,181336.0
5,P_00009,3,RIGHT,CC,1,mass,OVAL,ILL_DEFINED,4,MALIGNANT,4,Mass-Training_P_00009_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.348094436212980762312744999743818171955/1.3.6.1.4.1.9590.100.1.2.392091931911637760938815694332198115839/000000.dcm,Mass-Training_P_00009_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.242248988911264591618859462853814566714/1.3.6.1.4.1.9590.100.1.2.38355348211600094806469224183939342192/000000.dcm,Mass-Training_P_00009_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.242248988911264591618859462853814566714/1.3.6.1.4.1.9590.100.1.2.38355348211600094806469224183939342192/000001.dcm\n,1.3.6.1.4.1.9590.100.1.2.348094436212980762312744999743818171955,1.3.6.1.4.1.9590.100.1.2.392091931911637760938815694332198115839,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.392091931911637760938815694332198115839/1-275.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.392091931911637760938815694332198115839/1-275.jpg,NaN,16,16,BREAST,2206,20160414,121734.020,WSD,15,1,65534,R,MG,NaN,Mass-Training_P_00009_RIGHT_CC,Mass-Training_P_00009_RIGHT_CC,CC,NaN,MONOCHROME2,0,NaN,4441,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.194258849411092848026292238523588256282,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160720.0,DDSM,181337.0
6,P_00009,3,RIGHT,MLO,1,mass,OVAL,ILL_DEFINED,4,MALIGNANT,4,Mass-Training_P_00009_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.255880668112335952601613726063195485525/1.3.6.1.4.1.9590.100.1.2.18553022011298363903753970133853455201/000000.dcm,Mass-Training_P_00009_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.335609780010927131533324655753766075455/1.3.6.1.4.1.9590.100.1.2.401504763912518926442932683851439819951/000000.dcm,Mass-Training_P_00009_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.335609780010927131533324655753766075455/1.3.6.1.4.1.9590.100.1.2.401504763912518926442932683851439819951/000001.dcm\n,1.3.6.1.4.1.9590.100.1.2.255880668112335952601613726063195485525,1.3.6.1.4.1.9590.100.1.2.18553022011298363903753970133853455201,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.18553022011298363903753970133853455201/1-104.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.18553022011298363903753970133853455201/1-104.jpg,NaN,16,16,BREAST,2596,20160414,121737.920,WSD,15,1,65534,R,MG,NaN,Mass-Training_P_00009_RIGHT_MLO,Mass-Training_P_00009_RIGHT_MLO,MLO,NaN,MONOCHROME2,0,NaN,5266,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.276768881512610835827639622932683161075,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160720.0,DDSM,181338.0
7,P_00015,3,LEFT,MLO,1,mass,IRREGULAR,ILL_DEFINED-SPICULATED,4,MALIGNANT,4,Mass-Training_P_00015_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.401772036413964151122239013710383266724/1.3.6.1.4.1.9590.100.1.2.399831242111800621220027542190666363688/000000.dcm,Mass-Training_P_00015_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.88226023711289360709168377972019346937/1.3.6.1.4.1.9590.100.1.2.225307445711972492021703541080800178003/000000.dcm,Mass-Training_P_00015_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.88226023711289360709168377972019346937/1.3.6.1.4.1.9590.100.1.2.225307445711972492021703541080800178003/000001.dcm\n,1.3.6.1.4.1.9590.100.1.2.401772036413964151122239013710383266724,1.3.6.1.4.1.9590.100.1.2.399831242111800621220027542190666363688,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.399831242111800621220027542190666363688/1-046.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.399831242111800621220027542190666363688/1-046.jpg,NaN,16,16,BREAST,4000,20160414,121742.705,WSD,15,1,61714,L,MG,NaN,Mass-Training_P_00015_LEFT_MLO,Mass-Training_P_00015_LEFT_MLO,MLO,NaN,MONOCHROME2,0,NaN,5552,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.377937144412764328609401294082902189022,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160720.0,DDSM,181340.0
8,P_00018,2,RIGHT,CC,1,mass,OVAL,CIRCUMSCRIBED,4,BENIGN,5,Mass-Training_P_00018_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.95984463413128864010730858240882618937/1.3.6.1.4.1.9590.100.1.2.353764633213863442442494539840710764601/000000.dcm,Mass-Training_P_00018_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.128534382212443571339674961083697292063/1.3.6.1.4.1.9590.100.1.2.393707185513959554524123170961270881067/000000.dcm,Mass-Training_P_00018_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.128534382212443571339674961083697292063/1.3.6.1.4.1.9590.100.1.2.393707185513959554524123170961270881067/000001.dcm\n,1.3.6.1.4.1.9590.100.1.2.95984463413128864010730858240882618937,1.3.6.1.4.1.9590.100.1.2.353764633213863442442494539840710764601,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.353764633213863442442494539840710764601/1-092.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.353764633213863442442494539840710764601/1-092.jpg,NaN,16,16,BREAST,2584,20160414,121807.352,WSD,15,1,65535,R,MG,NaN,Mass-Training_P_00018_RIGHT_CC,Mass-Training_P_00018_RIGHT_CC,CC,NaN,MONOCHROME2,0,NaN,4720,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.182827685011807375537730530650857157062,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160720.0,DDSM,181342.0
9,P_00018,2,RIGHT,MLO,1,mass,OVAL,CIRCUMSCRIBED,4,BENIGN,5,Mass-Training_P_00018_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.185380682810337528808354106072261609956/1.3.6.1.4.1.9590.100.1.2.301773695910378556700140939623830965391/000000.dcm,Mass-Training_P_00018_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.101779170312160317816019480361869195813/1.3.6.1.4.1.9590.100.1.2.47910753912017870434385834703698378596/000000.dcm,Mass-Training_P_00018_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.101779170312160317816019480361869195813/1.3.6.1.4.1.9590.100.1.2.47910753912017870434385834703698378596/000001.dcm\n,1.3.6.1.4.1.9590.100.1.2.185380682810337528808354106072261609956,1.3.6.1.4.1.9590.100.1.2.301773695910378556700140939623830965391,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.301773695910378556700140939623830965391/1-082.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.301773695910378556700140939623830965391/1-082.jpg,NaN,16,16,BREAST,2544,20160414,121811.671,WSD,15,1,65535,R,MG,NaN,Mass-Training_P_00018_RIGHT_MLO,Mass-Training_P_00018_RIGHT_MLO,MLO,NaN,MONOCHROME2,0,NaN,4664,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.31654758313833800023269769451914769296,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160720.0,DDSM,181343.0

In [9]:
mass_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1318 entries, 0 to 1317
Data columns (total 59 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   patient_id                                   1318 non-null   object
 1   breast_density                               1318 non-null   int64
 2   left or right breast                         1318 non-null   object
 3   image view                                   1318 non-null   object
 4   abnormality id                               1318 non-null   int64
 5   abnormality type                             1318 non-null   object
 6   mass shape                                   1314 non-null   object
 7   mass margins                                 1275 non-null   object
 8   assessment                                   1318 non-null   int64
 9   pathology                                    1318 non-null   object
 10  subtlety                                     1318 non-null   int64
 11  image file path                              1318 non-null   object
 12  cropped image file path                      1318 non-null   object
 13  ROI mask file path                           1318 non-null   object
 14  StudyInstanceUID                             1318 non-null   object
 15  SeriesInstanceUID                            1318 non-null   object
 16  Modality_x                                   1318 non-null   object
 17  SeriesDescription_x                          1318 non-null   object
 18  BodyPartExamined_x                           1318 non-null   object
 19  SeriesNumber_x                               1318 non-null   int64
 20  Collection                                   1318 non-null   object
 21  Visibility                                   1318 non-null   int64
 22  ImageCount                                   1318 non-null   int64
 23  file_path                                    1318 non-null   object
 24  image_path                                   1318 non-null   object
 25  AccessionNumber                              0 non-null      float64
 26  BitsAllocated                                1318 non-null   int64
 27  BitsStored                                   1318 non-null   int64
 28  BodyPartExamined_y                           1318 non-null   object
 29  Columns                                      1318 non-null   int64
 30  ContentDate                                  1318 non-null   int64
 31  ContentTime                                  1318 non-null   float64
 32  ConversionType                               1318 non-null   object
 33  HighBit                                      1318 non-null   int64
 34  InstanceNumber                               1318 non-null   int64
 35  LargestImagePixelValue                       1318 non-null   int64
 36  Laterality                                   1318 non-null   object
 37  Modality_y                                   1318 non-null   object
 38  PatientBirthDate                             0 non-null      float64
 39  PatientID                                    1318 non-null   object
 40  PatientName                                  1318 non-null   object
 41  PatientOrientation                           1318 non-null   object
 42  PatientSex                                   0 non-null      float64
 43  PhotometricInterpretation                    1318 non-null   object
 44  PixelRepresentation                          1318 non-null   int64
 45  ReferringPhysicianName                       0 non-null      float64
 46  Rows                                         1318 non-null   int64
 47  SOPClassUID                                  1318 non-null   object
 48  SOPInstanceUID                               1318 non-null   object
 49  SamplesPerPixel                              1318 non-null   int64
 50  SecondaryCaptureDeviceManufacturer           1318 non-null   object
 51  SecondaryCaptureDeviceManufacturerModelName  1318 non-null   object
 52  SeriesDescription_y                          1318 non-null   object
 53  SeriesNumber_y                               1318 non-null   int64
 54  SmallestImagePixelValue                      1318 non-null   int64
 55  SpecificCharacterSet                         1318 non-null   object
 56  StudyDate                                    1318 non-null   float64
 57  StudyID                                      1318 non-null   object
 58  StudyTime                                    1318 non-null   float64
dtypes: float64(7), int64(19), object(33)
memory usage: 607.6+ KB

In [10]:
#Comprobamos que la info tiene sentido. Nos quedamos con las columnas importantes:
columnas_importantes = ['patient_id', 'PatientID', 'left or right breast', 
                        'breast_density', 'abnormality type', 'image file path', 'image_path',
                        'image view','SeriesDescription_x','SeriesDescription_y']
mass_full[columnas_importantes].head(7)

,patient_id,PatientID,left or right breast,breast_density,abnormality type,image file path,image_path,image view,SeriesDescription_x,SeriesDescription_y
0,P_00001,Mass-Training_P_00001_LEFT_CC,LEFT,3,mass,Mass-Training_P_00001_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.422112722213189649807611434612228974994/1.3.6.1.4.1.9590.100.1.2.342386194811267636608694132590482924515/000000.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.342386194811267636608694132590482924515/1-211.jpg,CC,full mammogram images,full mammogram images
1,P_00001,Mass-Training_P_00001_LEFT_MLO,LEFT,3,mass,Mass-Training_P_00001_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.319478999311971442426185353560182990988/1.3.6.1.4.1.9590.100.1.2.359308329312397897125630708681441180834/000000.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.359308329312397897125630708681441180834/1-207.jpg,MLO,full mammogram images,full mammogram images
2,P_00004,Mass-Training_P_00004_LEFT_CC,LEFT,3,mass,Mass-Training_P_00004_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.347107867812656628709864319310977895697/1.3.6.1.4.1.9590.100.1.2.89180046211022531834352631483669346540/000000.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.89180046211022531834352631483669346540/1-250.jpg,CC,full mammogram images,full mammogram images
3,P_00004,Mass-Training_P_00004_LEFT_MLO,LEFT,3,mass,Mass-Training_P_00004_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.272600286511817402806912403581910920939/1.3.6.1.4.1.9590.100.1.2.295360926313492745441868049270168300162/000000.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.295360926313492745441868049270168300162/1-067.jpg,MLO,full mammogram images,full mammogram images
4,P_00004,Mass-Training_P_00004_RIGHT_MLO,RIGHT,3,mass,Mass-Training_P_00004_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.174047308712169195014610267031196524486/1.3.6.1.4.1.9590.100.1.2.410524754913057908920631336070876889890/000000.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.410524754913057908920631336070876889890/1-056.jpg,MLO,full mammogram images,full mammogram images
5,P_00009,Mass-Training_P_00009_RIGHT_CC,RIGHT,3,mass,Mass-Training_P_00009_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.348094436212980762312744999743818171955/1.3.6.1.4.1.9590.100.1.2.392091931911637760938815694332198115839/000000.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.392091931911637760938815694332198115839/1-275.jpg,CC,full mammogram images,full mammogram images
6,P_00009,Mass-Training_P_00009_RIGHT_MLO,RIGHT,3,mass,Mass-Training_P_00009_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.255880668112335952601613726063195485525/1.3.6.1.4.1.9590.100.1.2.18553022011298363903753970133853455201/000000.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.18553022011298363903753970133853455201/1-104.jpg,MLO,full mammogram images,full mammogram images

In [11]:
print(mass_full['SeriesDescription_x'].value_counts())
print(mass_full['SeriesDescription_y'].value_counts())

SeriesDescription_x
full mammogram images    1318
Name: count, dtype: int64
SeriesDescription_y
full mammogram images    1318
Name: count, dtype: int64

In [24]:
#Vamos a cambiar el nombre de las imágenes que están en calc_full para que contengan toda la info que queremos
import shutil
import os

base_path = r'C:\Users\pedro\.cache\kagglehub\datasets\awsaf49\cbis-ddsm-breast-cancer-image-dataset\versions\1\jpeg'

def construir_ruta_real(image_path_csv):
    # 1. Separar por "/"
    partes = image_path_csv.split("/")

    # 2. El StudyInstanceUID está en la segunda parte
    study_uid = partes[2]

    # 3. El nombre del archivo está en la última parte, pero en Kaggle es .jpg
    filename = partes[-1]

    # 4. Construir ruta real
    ruta_real = os.path.join(base_path, study_uid, filename)

    return ruta_real
#También vamos a guardar solo el último filename

def guardar_filename(image_path_csv):
    # 1. Separar por "/"
    partes = image_path_csv.split("/")

    # 2. El StudyInstanceUID está en la segunda parte
    study_uid = partes[2]

    # 3. El nombre del archivo está en la última parte, pero en Kaggle es .jpg
    filename = partes[-1]

    # 4. Construir ruta real
    ruta_real = filename

    return ruta_real

In [25]:
mass_full["ruta_real"] = mass_full["image_path"].apply(construir_ruta_real)
mass_full['filename'] = mass_full['image_path'].apply(guardar_filename)

In [26]:
mass_full[['ruta_real','filename']].head(8)

,ruta_real,filename
0,C:\Users\pedro\.cache\kagglehub\datasets\awsaf49\cbis-ddsm-breast-cancer-image-dataset\versions\1\jpeg\1.3.6.1.4.1.9590.100.1.2.342386194811267636608694132590482924515\1-211.jpg,1-211.jpg
1,C:\Users\pedro\.cache\kagglehub\datasets\awsaf49\cbis-ddsm-breast-cancer-image-dataset\versions\1\jpeg\1.3.6.1.4.1.9590.100.1.2.359308329312397897125630708681441180834\1-207.jpg,1-207.jpg
2,C:\Users\pedro\.cache\kagglehub\datasets\awsaf49\cbis-ddsm-breast-cancer-image-dataset\versions\1\jpeg\1.3.6.1.4.1.9590.100.1.2.89180046211022531834352631483669346540\1-250.jpg,1-250.jpg
3,C:\Users\pedro\.cache\kagglehub\datasets\awsaf49\cbis-ddsm-breast-cancer-image-dataset\versions\1\jpeg\1.3.6.1.4.1.9590.100.1.2.295360926313492745441868049270168300162\1-067.jpg,1-067.jpg
4,C:\Users\pedro\.cache\kagglehub\datasets\awsaf49\cbis-ddsm-breast-cancer-image-dataset\versions\1\jpeg\1.3.6.1.4.1.9590.100.1.2.410524754913057908920631336070876889890\1-056.jpg,1-056.jpg
5,C:\Users\pedro\.cache\kagglehub\datasets\awsaf49\cbis-ddsm-breast-cancer-image-dataset\versions\1\jpeg\1.3.6.1.4.1.9590.100.1.2.392091931911637760938815694332198115839\1-275.jpg,1-275.jpg
6,C:\Users\pedro\.cache\kagglehub\datasets\awsaf49\cbis-ddsm-breast-cancer-image-dataset\versions\1\jpeg\1.3.6.1.4.1.9590.100.1.2.18553022011298363903753970133853455201\1-104.jpg,1-104.jpg
7,C:\Users\pedro\.cache\kagglehub\datasets\awsaf49\cbis-ddsm-breast-cancer-image-dataset\versions\1\jpeg\1.3.6.1.4.1.9590.100.1.2.399831242111800621220027542190666363688\1-046.jpg,1-046.jpg

In [27]:

    #Creamos el nombre que queremos hacer a la imagen
mass_full["nombre_imagenes"] = (
    mass_full["pathology"].astype(str) + "_" +
    mass_full["left or right breast"].astype(str) + "_" +
    mass_full["image view"].astype(str)  + "_" +
    mass_full['mass shape'].astype(str) + "_" +
    mass_full['mass margins'].astype(str) + "_" +
    mass_full['filename'].astype(str)
)
mass_full['nombre_imagenes'].head(8)

0     MALIGNANT_LEFT_CC_IRREGULAR-ARCHITECTURAL_DISTORTION_SPICULATED_1-211.jpg
1    MALIGNANT_LEFT_MLO_IRREGULAR-ARCHITECTURAL_DISTORTION_SPICULATED_1-207.jpg
2                 BENIGN_LEFT_CC_ARCHITECTURAL_DISTORTION_ILL_DEFINED_1-250.jpg
3                BENIGN_LEFT_MLO_ARCHITECTURAL_DISTORTION_ILL_DEFINED_1-067.jpg
4                                 BENIGN_RIGHT_MLO_OVAL_CIRCUMSCRIBED_1-056.jpg
5                                 MALIGNANT_RIGHT_CC_OVAL_ILL_DEFINED_1-275.jpg
6                                MALIGNANT_RIGHT_MLO_OVAL_ILL_DEFINED_1-104.jpg
7                 MALIGNANT_LEFT_MLO_IRREGULAR_ILL_DEFINED-SPICULATED_1-046.jpg
Name: nombre_imagenes, dtype: object

In [30]:
#Aplicamos con shutil
path_destino = r'C:\Users\pedro\Documents\MÁSTER UNIR 💻\TFM\extracción de imágenes del dataset\Imagenes'

for i in range(0,len(mass_full)):
    ruta_origen = mass_full['ruta_real'][i]
    ruta_destino_completa = os.path.join(path_destino, mass_full['nombre_imagenes'][i])
    shutil.copy(ruta_origen,ruta_destino_completa)

1. Esquema de combinación razonable
Opción fuerte y limpia:

INbreast → Segmentación supervisada

Entrenas una U‑Net/nnU‑Net para segmentar masas/calcificaciones.

Métricas: Dice, IoU, etc.

Dataset pequeño pero con GT perfecto.

INbreast → Clasificación a partir de máscaras o crops

A partir de las máscaras, generas:

crops alrededor de la lesión

o features agregadas (área, forma, etc.)

Entrenas un clasificador benigno/maligno (si las etiquetas lo permiten) o por tipo de lesión.

Kaggle CBIS → Clasificación en full mammograms

Usas solo las full mammo que ya tienes mapeadas.

Tarea: benigno/maligno, calc/calc, etc.

Modelo tipo ResNet/ViT.

Localización débil: Grad‑CAM sobre las full mammo.

Generalización cruzada

Entrenas en INbreast, pruebas en Kaggle (si las etiquetas son compatibles).

Entrenas en Kaggle, pruebas en INbreast.

Discutes dominio, cambio de distribución, diferencias de adquisición, etc.

In [31]:
#Hacemos lo mismo con calc
# ============================
# 2. CARGAR CSVs
# ============================

calc = pd.read_csv('calc_case_description_train_set.csv')
meta = pd.read_csv('meta.csv')
dicom = pd.read_csv('dicom_info.csv')

# ============================
# 3. EXTRAER StudyUID y SeriesUID DEL image_file_path
# ============================

calc["StudyInstanceUID"] = calc["image file path"].str.split("/").str[1]
calc["SeriesInstanceUID"] = calc["image file path"].str.split("/").str[2]

# ============================
# 4. MERGE calc ↔ META (para saber cuántas imágenes tiene la serie)
# ============================

calc_meta = calc.merge(meta, on=["StudyInstanceUID", "SeriesInstanceUID"], how="left")

# ============================
# 5. MERGE calc_META ↔ DICOM_INFO (para obtener rutas JPEG reales)
# ============================

calc_full = calc_meta.merge(dicom, on=["StudyInstanceUID", "SeriesInstanceUID"], how="left")
calc_full.head(10)

,patient_id,breast density,left or right breast,image view,abnormality id,abnormality type,calc type,calc distribution,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path,StudyInstanceUID,SeriesInstanceUID,Modality_x,SeriesDescription_x,BodyPartExamined_x,SeriesNumber_x,Collection,Visibility,ImageCount,file_path,image_path,AccessionNumber,BitsAllocated,BitsStored,BodyPartExamined_y,Columns,ContentDate,ContentTime,ConversionType,HighBit,InstanceNumber,LargestImagePixelValue,Laterality,Modality_y,PatientBirthDate,PatientID,PatientName,PatientOrientation,PatientSex,PhotometricInterpretation,PixelRepresentation,ReferringPhysicianName,Rows,SOPClassUID,SOPInstanceUID,SamplesPerPixel,SecondaryCaptureDeviceManufacturer,SecondaryCaptureDeviceManufacturerModelName,SeriesDescription_y,SeriesNumber_y,SmallestImagePixelValue,SpecificCharacterSet,StudyDate,StudyID,StudyTime
0,P_00005,3,RIGHT,CC,1,calcification,AMORPHOUS,CLUSTERED,3,MALIGNANT,3,Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.408909860712120272633130274602115723157/1.3.6.1.4.1.9590.100.1.2.47414316010368386519740343172775938548/000000.dcm,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.328778919012412769218080124214088709081/1.3.6.1.4.1.9590.100.1.2.393344010211719049419601138200355094682/000001.dcm\n,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.328778919012412769218080124214088709081/1.3.6.1.4.1.9590.100.1.2.393344010211719049419601138200355094682/000000.dcm,1.3.6.1.4.1.9590.100.1.2.408909860712120272633130274602115723157,1.3.6.1.4.1.9590.100.1.2.47414316010368386519740343172775938548,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.47414316010368386519740343172775938548/1-188.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.47414316010368386519740343172775938548/1-188.jpg,NaN,16,16,BREAST,2761,20160503,105435.478,WSD,15,1,65535,R,MG,NaN,Calc-Training_P_00005_RIGHT_CC,Calc-Training_P_00005_RIGHT_CC,CC,NaN,MONOCHROME2,0,NaN,5056,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.378776769711002686209961163603436313519,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160807.0,DDSM,161037.0
1,P_00005,3,RIGHT,MLO,1,calcification,AMORPHOUS,CLUSTERED,3,MALIGNANT,3,Calc-Training_P_00005_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.427517897311902339923511678883689433338/1.3.6.1.4.1.9590.100.1.2.250596608311207922527805669693579696727/000000.dcm,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.67512362210319636108148504382680781938/1.3.6.1.4.1.9590.100.1.2.296281207812130400303493285473798422894/000001.dcm\n,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.67512362210319636108148504382680781938/1.3.6.1.4.1.9590.100.1.2.296281207812130400303493285473798422894/000000.dcm,1.3.6.1.4.1.9590.100.1.2.427517897311902339923511678883689433338,1.3.6.1.4.1.9590.100.1.2.250596608311207922527805669693579696727,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.250596608311207922527805669693579696727/1-189.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.250596608311207922527805669693579696727/1-189.jpg,NaN,16,16,BREAST,2836,20160503,105440.625,WSD,15,1,65535,R,MG,NaN,Calc-Training_P_00005_RIGHT_MLO,Calc-Training_P_00005_RIGHT_MLO,MLO,NaN,MONOCHROME2,0,NaN,5386,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.344560194211255710311153402222519334809,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160807.0,DDSM,161039.0
2,P_00007,4,LEFT,CC,1,calcification,PLEOMORPHIC,LINEAR,4,BENIGN,4,Calc-Training_P_00007_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.201322325113694962619881476352450072222/1.3.6.1.4.1.9590.100.1.2.228699627313487111012474405462022068297/000000.dcm,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.241202057913673145232234613012384759880/1.3.6.1.4.1.9590.100.1.2.314135871111943890422150247820137952041/000001.dcm\n,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.241202057913673145232234613012384759880/1.3.6.1.4.1.9590.100.1.2.314135871111943890422150247820137952041/000000.dcm,1.3.6.1.4.1.9590.100.1.2.201322325113694962619881476352450072222,1.3.6.1.4.1.9590.100.1.2.228699627313487111012474405462022068297,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.228699627313487111012474405462022068297/1-190.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.228699627313487111012474405462022068297/1-190.jpg,NaN,16,16,BREAST,2986,20160503,105456.806,WSD,15,1,65535,L,MG,NaN,Calc-Training_P_00007_LEFT_CC,Calc-Training_P_00007_LEFT_CC,CC,NaN,MONOCHROME2,0,NaN,5356,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.289523209011022171720217609472887741681,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160807.0,DDSM,161042.0
3,P_00007,4,LEFT,MLO,1,calcification,PLEOMORPHIC,LINEAR,4,BENIGN,4,Calc-Training_P_00007_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.370479499712916693322010643793108454887/1.3.6.1.4.1.9590.100.1.2.104743410411133110629448544090466900446/000000.dcm,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.314250272911170289203882349024229868823/1.3.6.1.4.1.9590.100.1.2.91458279612485515203413781822560852485/000001.dcm\n,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.314250272911170289203882349024229868823/1.3.6.1.4.1.9590.100.1.2.91458279612485515203413781822560852485/000000.dcm,1.3.6.1.4.1.9590.100.1.2.370479499712916693322010643793108454887,1.3.6.1.4.1.9590.100.1.2.104743410411133110629448544090466900446,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.104743410411133110629448544090466900446/1-191.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.104743410411133110629448544090466900446/1-191.jpg,NaN,16,16,BREAST,3166,20160503,105502.792,WSD,15,1,65535,L,MG,NaN,Calc-Training_P_00007_LEFT_MLO,Calc-Training_P_00007_LEFT_MLO,MLO,NaN,MONOCHROME2,0,NaN,5491,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.140012230311051260141018615363263685110,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160807.0,DDSM,161045.0
4,P_00008,1,LEFT,CC,1,calcification,NaN,REGIONAL,2,BENIGN_WITHOUT_CALLBACK,3,Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/000000.dcm,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.336811694512764490002272925921108351157/1.3.6.1.4.1.9590.100.1.2.281397494612871934937455783843630775495/000001.dcm\n,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.336811694512764490002272925921108351157/1.3.6.1.4.1.9590.100.1.2.281397494612871934937455783843630775495/000000.dcm,1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189,1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/1-192.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/1-192.jpg,NaN,16,16,BREAST,3064,20160503,105521.977,WSD,15,1,65535,L,MG,NaN,Calc-Training_P_00008_LEFT_CC,Calc-Training_P_00008_LEFT_CC,CC,NaN,MONOCHROME2,0,NaN,4568,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.289949632412471538239723457783406978017,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160807.0,DDSM,161048.0
5,P_00008,1,LEFT,CC,2,calcification,NaN,REGIONAL,2,BENIGN_WITHOUT_CALLBACK,3,Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/000000.dcm,Calc-Training_P_00008_LEFT_CC_2/1.3.6.1.4.1.9590.100.1.2.207558519313356140106496367610041842177/1.3.6.1.4.1.9590.100.1.2.2024181113538627406890441552979568519/000001.dcm\n,Calc-Training_P_00008_LEFT_CC_2/1.3.6.1.4.1.9590.100.1.2.207558519313356140106496367610041842177/1.3.6.1.4.1.9590.100.1.2.2024181113538627406890441552979568519/000000.dcm,1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189,1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/1-192.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/1-192.jpg,NaN,16,16,BREAST,3064,20160503,105521.977,WSD,15,1,65535,L,MG,NaN,Calc-Training_P_00008_LEFT_CC,Calc-Training_P_00008_LEFT_CC,CC,NaN,MONOCHROME2,0,NaN,4568,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.289949632412471538239723457783406978017,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160807.0,DDSM,161048.0
6,P_00008,1,LEFT,CC,3,calcification,NaN,REGIONAL,2,BENIGN_WITHOUT_CALLBACK,3,Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/000000.dcm,Calc-Training_P_00008_LEFT_CC_3/1.3.6.1.4.1.9590.100.1.2.74480335312443720440103727953726257477/1.3.6.1.4.1.9590.100.1.2.358964325411863896506852883280957478483/000001.dcm\n,Calc-Training_P_00008_LEFT_CC_3/1.3.6.1.4.1.9590.100.1.2.74480335312443720440103727953726257477/1.3.6.1.4.1.9590.100.1.2.358964325411863896506852883280957478483/000000.dcm,1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189,1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/1-192.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/1-192.jpg,NaN,16,16,BREAST,3064,20160503,105521.977,WSD,15,1,65535,L,MG,NaN,Calc-Training_P_00008_LEFT_CC,Calc-Training_P_00008_LEFT_CC,CC,NaN,MONOCHROME2,0,NaN,4568,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.289949632412471538239723457783406978017,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160807.0,DDSM,161048.0
7,P_00008,1,LEFT,MLO,1,calcification,NaN,REGIONAL,2,BENIGN_WITHOUT_CALLBACK,3,Calc-Training_P_00008_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.84155842712765660429462608981255328663/1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907/000000.dcm,Calc-Training_P_00008_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.194216643012943010222741170453094926786/1.3.6.1.4.1.9590.100.1.2.81216723513826953322779836314123146864/000001.dcm\n,Calc-Training_P_00008_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.194216643012943010222741170453094926786/1.3.6.1.4.1.9590.100.1.2.81216723513826953322779836314123146864/000000.dcm,1.3.6.1.4.1.9590.100.1.2.84155842712765660429462608981255328663,1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907/1-193.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907/1-193.jpg,NaN,16,16,BREAST,3056,20160503,105540.141,WSD,15,1,65535,L,MG,NaN,Calc-Training_P_00008_LEFT_MLO,Calc-Training_P_00008_LEFT_MLO,MLO,NaN,MONOCHROME2,0,NaN,4528,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.212038222410702650307328900311344307729,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160807.0,DDSM,161051.0
8,P_00008,1,LEFT,MLO,2,calcification,NaN,REGIONAL,2,BENIGN_WITHOUT_CALLBACK,3,Calc-Training_P_00008_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.84155842712765660429462608981255328663/1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907/000000.dcm,Calc-Training_P_00008_LEFT_MLO_2/1.3.6.1.4.1.9590.100.1.2.363735588611036329226111671323507141479/1.3.6.1.4.1.9590.100.1.2.101644730412034535338273957660005319377/000001.dcm\n,Calc-Training_P_00008_LEFT_MLO_2/1.3.6.1.4.1.9590.100.1.2.363735588611036329226111671323507141479/1.3.6.1.4.1.9590.100.1.2.101644730412034535338273957660005319377/000000.dcm,1.3.6.1.4.1.9590.100.1.2.84155842712765660429462608981255328663,1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907/1-193.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907/1-193.jpg,NaN,16,16,BREAST,3056,20160503,105540.141,WSD,15,1,65535,L,MG,NaN,Calc-Training_P_00008_LEFT_MLO,Calc-Training_P_00008_LEFT_MLO,MLO,NaN,MONOCHROME2,0,NaN,4528,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.212038222410702650307328900311344307729,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160807.0,DDSM,161051.0
9,P_00008,1,LEFT,MLO,3,calcification,NaN,REGIONAL,2,BENIGN_WITHOUT_CALLBACK,3,Calc-Training_P_00008_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.84155842712765660429462608981255328663/1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907/000000.dcm,Calc-Training_P_00008_LEFT_MLO_3/1.3.6.1.4.1.9590.100.1.2.161386321913969368010907593284201308852/1.3.6.1.4.1.9590.100.1.2.4165882011639284134385639942174899929/000001.dcm\n,Calc-Training_P_00008_LEFT_MLO_3/1.3.6.1.4.1.9590.100.1.2.161386321913969368010907593284201308852/1.3.6.1.4.1.9590.100.1.2.4165882011639284134385639942174899929/000000.dcm,1.3.6.1.4.1.9590.100.1.2.84155842712765660429462608981255328663,1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907,MG,full mammogram images,BREAST,1,CBIS-DDSM,1,1,CBIS-DDSM/dicom/1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907/1-193.dcm,CBIS-DDSM/jpeg/1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907/1-193.jpg,NaN,16,16,BREAST,3056,20160503,105540.141,WSD,15,1,65535,L,MG,NaN,Calc-Training_P_00008_LEFT_MLO,Calc-Training_P_00008_LEFT_MLO,MLO,NaN,MONOCHROME2,0,NaN,4528,1.2.840.10008.5.1.4.1.1.7,1.3.6.1.4.1.9590.100.1.2.212038222410702650307328900311344307729,1,MathWorks,MATLAB,full mammogram images,1,0,ISO_IR 100,20160807.0,DDSM,161051.0

In [34]:
calc_full["ruta_real"] = calc_full["image_path"].apply(construir_ruta_real)
calc_full['filename'] = calc_full['image_path'].apply(guardar_filename)

    #Creamos el nombre que queremos hacer a la imagen
calc_full["nombre_imagenes"] = (
    calc_full["pathology"].astype(str) + "_" +
    calc_full["left or right breast"].astype(str) + "_" +
    calc_full["image view"].astype(str)  + "_" +
    calc_full['calc type'].astype(str) + "_" +
    calc_full['calc distribution'].astype(str) + "_" +
    calc_full['filename'].astype(str)
)
calc_full['nombre_imagenes'].head(8)

0           MALIGNANT_RIGHT_CC_AMORPHOUS_CLUSTERED_1-188.jpg
1          MALIGNANT_RIGHT_MLO_AMORPHOUS_CLUSTERED_1-189.jpg
2                BENIGN_LEFT_CC_PLEOMORPHIC_LINEAR_1-190.jpg
3               BENIGN_LEFT_MLO_PLEOMORPHIC_LINEAR_1-191.jpg
4     BENIGN_WITHOUT_CALLBACK_LEFT_CC_nan_REGIONAL_1-192.jpg
5     BENIGN_WITHOUT_CALLBACK_LEFT_CC_nan_REGIONAL_1-192.jpg
6     BENIGN_WITHOUT_CALLBACK_LEFT_CC_nan_REGIONAL_1-192.jpg
7    BENIGN_WITHOUT_CALLBACK_LEFT_MLO_nan_REGIONAL_1-193.jpg
Name: nombre_imagenes, dtype: object

In [35]:
#Aplicamos con shutil
path_destino = r'C:\Users\pedro\Documents\MÁSTER UNIR 💻\TFM\extracción de imágenes del dataset\Imagenes Calcification'

for i in range(0,len(calc_full)):
    ruta_origen = calc_full['ruta_real'][i]
    ruta_destino_completa = os.path.join(path_destino, calc_full['nombre_imagenes'][i])
    shutil.copy(ruta_origen,ruta_destino_completa)